import type { RNG } from './rng';
import type { Token, Word, WordType } from './types';

// お題の語彙。display=表示（漢字交じり）, reading=読み（かな・判定の元）。
interface WordEntry {
  display: string;
  reading: string;
}

export const WORD_POOL: WordEntry[] = [
  // あいさつ・日常
  { display: 'ありがとう', reading: 'ありがとう' },
  { display: 'こんにちは', reading: 'こんにちは' },
  { display: '宜しく', reading: 'よろしく' },
  { display: '頑張って', reading: 'がんばって' },
  { display: 'お疲れ様', reading: 'おつかれさま' },
  { display: '初めまして', reading: 'はじめまして' },
  // IT・ゲーム
  { display: 'タイピング', reading: 'たいぴんぐ' },
  { display: 'キーボード', reading: 'きーぼーど' },
  { display: 'マウス', reading: 'まうす' },
  { display: 'パソコン', reading: 'ぱそこん' },
  { display: 'インターネット', reading: 'いんたーねっと' },
  { display: 'プログラミング', reading: 'ぷろぐらみんぐ' },
  { display: '技術者', reading: 'ぎじゅつしゃ' },
  { display: '開発', reading: 'かいはつ' },
  { display: '画面', reading: 'がめん' },
  { display: '電源', reading: 'でんげん' },
  { display: '通信', reading: 'つうしん' },
  { display: '対戦', reading: 'たいせん' },
  { display: '連鎖', reading: 'れんさ' },
  { display: '攻撃', reading: 'こうげき' },
  { display: '逆転', reading: 'ぎゃくてん' },
  { display: '勝利', reading: 'しょうり' },
  { display: '宝物', reading: 'たからもの' },
  { display: '道具', reading: 'どうぐ' },
  // 食べ物
  { display: 'お握り', reading: 'おにぎり' },
  { display: 'ハンバーガー', reading: 'はんばーがー' },
  { display: '拉麺', reading: 'らーめん' },
  { display: '林檎', reading: 'りんご' },
  { display: '蜜柑', reading: 'みかん' },
  { display: '西瓜', reading: 'すいか' },
  { display: '寿司', reading: 'すし' },
  { display: '味噌汁', reading: 'みそしる' },
  { display: '玉子焼き', reading: 'たまごやき' },
  { display: '珈琲', reading: 'こーひー' },
  // 自然・乗り物
  { display: '太陽', reading: 'たいよう' },
  { display: '宇宙', reading: 'うちゅう' },
  { display: '青空', reading: 'あおぞら' },
  { display: '新幹線', reading: 'しんかんせん' },
  { display: '飛行機', reading: 'ひこうき' },
  { display: '自転車', reading: 'じてんしゃ' },
  { display: '電車', reading: 'でんしゃ' },
  { display: '海', reading: 'うみ' },
  { display: '山', reading: 'やま' },
  { display: '川', reading: 'かわ' },
  { display: '森林', reading: 'しんりん' },
  { display: '稲妻', reading: 'いなずま' },
  // 学校・生活
  { display: '小学校', reading: 'しょうがっこう' },
  { display: '大学', reading: 'だいがく' },
  { display: '図書館', reading: 'としょかん' },
  { display: '宿題', reading: 'しゅくだい' },
  { display: '友達', reading: 'ともだち' },
  { display: '家族', reading: 'かぞく' },
  { display: '音楽', reading: 'おんがく' },
  { display: '映画', reading: 'えいが' },
  { display: '物語', reading: 'ものがたり' },
  { display: '挑戦', reading: 'ちょうせん' },
  { display: '冒険', reading: 'ぼうけん' },
  { display: '出発', reading: 'しゅっぱつ' },
  { display: '一番', reading: 'いちばん' },
  { display: '全力', reading: 'ぜんりょく' },
  { display: '集中', reading: 'しゅうちゅう' },
  { display: '反撃', reading: 'はんげき' },
  { display: '相殺', reading: 'そうさい' },
  // 追加語彙
  { display: '人懐っこい', reading: 'ひとなつっこい' },
  { display: '熱放射', reading: 'ねつほうしゃ' },
  { display: '貿易', reading: 'ぼうえき' },
  { display: 'クラクション', reading: 'くらくしょん' },
  { display: '掛け軸', reading: 'かけじく' },
  { display: '人混み', reading: 'ひとごみ' },
  { display: '調理実習', reading: 'ちょうりじっしゅう' },
  { display: '横顔', reading: 'よこがお' },
  { display: '受験勉強', reading: 'じゅけんべんきょう' },
  { display: 'クリスタル', reading: 'くりすたる' },
  { display: '醤油', reading: 'しょうゆ' },
  { display: '回文', reading: 'かいぶん' },
  { display: 'どん底', reading: 'どんぞこ' },
  { display: '有権者', reading: 'ゆうけんしゃ' },
  { display: '鼻毛', reading: 'はなげ' },
  { display: '赤目', reading: 'あかめ' },
  { display: '月曜日', reading: 'げつようび' },
  { display: '倒置法', reading: 'とうちほう' },
  { display: 'ネットゲーム', reading: 'ねっとげーむ' },
  { display: 'グリーンピース', reading: 'ぐりーんぴーす' },
  { display: 'カモノハシ', reading: 'かものはし' },
  { display: 'かみなり雲', reading: 'かみなりぐも' },
  { display: '問題解決', reading: 'もんだいかいけつ' },
  { display: 'スポンサー', reading: 'すぽんさー' },
  { display: '戦闘服', reading: 'せんとうふく' },
  { display: '湿る', reading: 'しめる' },
  { display: '乱発', reading: 'らんぱつ' },
  { display: '原材料', reading: 'げんざいりょう' },
  { display: '路線変更', reading: 'ろせんへんこう' },
  { display: '遠足', reading: 'えんそく' },
  { display: 'ホットココア', reading: 'ほっとここあ' },
  { display: '少女漫画', reading: 'しょうじょまんが' },
  { display: '洞察力', reading: 'どうさつりょく' },
  { display: '出演', reading: 'しゅつえん' },
  { display: '昆虫標本', reading: 'こんちゅうひょうほん' },
  { display: '充電', reading: 'じゅうでん' },
  { display: 'トレーニング', reading: 'とれーにんぐ' },
  { display: '両思い', reading: 'りょうおもい' },
  { display: '卒業アルバム', reading: 'そつぎょうあるばむ' },
  { display: 'コンビニスイーツ', reading: 'こんびにすいーつ' },
  { display: '懸賞金', reading: 'けんしょうきん' },
  { display: '外来種', reading: 'がいらいしゅ' },
  { display: 'メリーゴーランド', reading: 'めりーごーらんど' },
  { display: 'かりあげ', reading: 'かりあげ' },
  { display: 'サラリーマン', reading: 'さらりーまん' },
  { display: 'まばら', reading: 'まばら' },
  { display: '聴診器', reading: 'ちょうしんき' },
  { display: '玉虫色', reading: 'たまむしいろ' },
  { display: '有刺鉄線', reading: 'ゆうしてっせん' },
  // 追加語彙 2
  { display: '焼きそばパン', reading: 'やきそばぱん' },
  { display: '変わらない', reading: 'かわらない' },
  { display: '通販サイト', reading: 'つうはんさいと' },
  { display: '一握り', reading: 'ひとにぎり' },
  { display: '送料無料', reading: 'そうりょうむりょう' },
  { display: '誕生石', reading: 'たんじょうせき' },
  { display: 'だきまくら', reading: 'だきまくら' },
  { display: 'お笑いコンビ', reading: 'おわらいこんび' },
  { display: '殿堂入り', reading: 'でんどういり' },
  { display: '大騒ぎ', reading: 'おおさわぎ' },
  { display: '司会者', reading: 'しかいしゃ' },
  { display: '予想通り', reading: 'よそうどおり' },
  { display: '音楽番組', reading: 'おんがくばんぐみ' },
  { display: '機種変更', reading: 'きしゅへんこう' },
  { display: 'ナルト', reading: 'なると' },
  { display: 'あられ', reading: 'あられ' },
  { display: 'お祓い', reading: 'おはらい' },
  { display: 'ゲーム機', reading: 'げーむき' },
  { display: '江戸時代', reading: 'えどじだい' },
  { display: 'トラベラー', reading: 'とらべらー' },
  { display: '正義は勝つ', reading: 'せいぎはかつ' },
  { display: '保証金', reading: 'ほしょうきん' },
  { display: 'ホラー漫画', reading: 'ほらーまんが' },
  { display: '準決勝', reading: 'じゅんけっしょう' },
  { display: 'ショートケーキ', reading: 'しょーとけーき' },
  { display: 'ヨーロッパ', reading: 'よーろっぱ' },
  { display: '二十面相', reading: 'にじゅうめんそう' },
  { display: 'パズルゲーム', reading: 'ぱずるげーむ' },
  { display: '日本地図', reading: 'にほんちず' },
  { display: '生卵', reading: 'なまたまご' },
  { display: '朝方', reading: 'あさがた' },
  { display: '囁く', reading: 'ささやく' },
  { display: '呼吸法', reading: 'こきゅうほう' },
  { display: 'シャボン玉', reading: 'しゃぼんだま' },
  { display: '哺乳類', reading: 'ほにゅうるい' },
  { display: 'イノベーション', reading: 'いのべーしょん' },
  { display: 'コンディショナー', reading: 'こんでぃしょなー' },
  { display: '現行犯', reading: 'げんこうはん' },
  { display: '競馬', reading: 'けいば' },
  { display: 'キャンセル料', reading: 'きゃんせるりょう' },
  { display: '爪痕', reading: 'つめあと' },
  { display: '大使', reading: 'たいし' },
  { display: '数学', reading: 'すうがく' },
  { display: 'もやし', reading: 'もやし' },
  { display: '百万年後', reading: 'ひゃくまんねんご' },
  { display: '老人ホーム', reading: 'ろうじんほーむ' },
  { display: '世代交代', reading: 'せだいこうたい' },
  { display: '繰り返す', reading: 'くりかえす' },
  { display: '優勝カップ', reading: 'ゆうしょうかっぷ' },
  { display: 'バーテンダー', reading: 'ばーてんだー' },
  // 追加語彙 3
  { display: '二階から目薬', reading: 'にかいからめぐすり' },
  { display: 'クレーター', reading: 'くれーたー' },
  { display: '心の目', reading: 'こころのめ' },
  { display: '朝寝坊', reading: 'あさねぼう' },
  { display: '影絵', reading: 'かげえ' },
  { display: '裏切り', reading: 'うらぎり' },
  { display: '羊', reading: 'ひつじ' },
  { display: '高級車', reading: 'こうきゅうしゃ' },
  { display: 'ホールインワン', reading: 'ほーるいんわん' },
  { display: '化学反応', reading: 'かがくはんのう' },
  { display: '繰り出す', reading: 'くりだす' },
  { display: '直談判', reading: 'じかだんぱん' },
  { display: '小学生', reading: 'しょうがくせい' },
  { display: '百発百中', reading: 'ひゃっぱつひゃくちゅう' },
  { display: '幸か不幸か', reading: 'こうかふこうか' },
  { display: 'ヘアアイロン', reading: 'へああいろん' },
  { display: '挙動不審', reading: 'きょどうふしん' },
  { display: 'シークワーサー', reading: 'しーくわーさー' },
  { display: '無', reading: 'む' },
  { display: 'コンビニエンスストア', reading: 'こんびにえんすすとあ' },
  { display: '急転直下', reading: 'きゅうてんちょっか' },
  { display: '晴れ', reading: 'はれ' },
  { display: '写真週刊誌', reading: 'しゃしんしゅうかんし' },
  { display: '十進法', reading: 'じっしんほう' },
  { display: '弁当箱', reading: 'べんとうばこ' },
  { display: '無人駅', reading: 'むじんえき' },
  { display: '運転手', reading: 'うんてんしゅ' },
  { display: 'お布団', reading: 'おふとん' },
  { display: '保健室', reading: 'ほけんしつ' },
  { display: '誤解', reading: 'ごかい' },
  { display: '花吹雪', reading: 'はなふぶき' },
  { display: '間一髪', reading: 'かんいっぱつ' },
  { display: '草食系男子', reading: 'そうしょくけいだんし' },
  { display: '神がかり', reading: 'かみがかり' },
  { display: '国語', reading: 'こくご' },
  { display: 'ぼたもち', reading: 'ぼたもち' },
  { display: '放送事故', reading: 'ほうそうじこ' },
  { display: '進捗を生む', reading: 'しんちょくをうむ' },
  { display: '皮', reading: 'かわ' },
  { display: '昼下がり', reading: 'ひるさがり' },
  { display: '言葉遣い', reading: 'ことばづかい' },
  { display: '河原', reading: 'かわら' },
  { display: '挨拶代わり', reading: 'あいさつがわり' },
  { display: 'ホットミルク', reading: 'ほっとみるく' },
  { display: '奇妙', reading: 'きみょう' },
  { display: 'フンコロガシ', reading: 'ふんころがし' },
  { display: 'ピストル', reading: 'ぴすとる' },
  { display: 'アイマスク', reading: 'あいますく' },
];

// ローマ字入力マッピング（柔軟な入力に対応）
export const ROMAJI_MAP: Record<string, string[]> = {
  'あ': ['a'], 'い': ['i'], 'う': ['u', 'wu'], 'え': ['e'], 'お': ['o'],
  'か': ['ka', 'ca'], 'き': ['ki'], 'く': ['ku', 'cu', 'qu'], 'け': ['ke'], 'こ': ['ko', 'co'],
  'さ': ['sa'], 'し': ['shi', 'si', 'ci'], 'す': ['su'], 'せ': ['se', 'ce'], 'そ': ['so'],
  'た': ['ta'], 'ち': ['chi', 'ti'], 'つ': ['tsu', 'tu'], 'て': ['te'], 'と': ['to'],
  'な': ['na'], 'に': ['ni'], 'ぬ': ['nu'], 'ね': ['ne'], 'の': ['no'],
  'は': ['ha'], 'ひ': ['hi'], 'ふ': ['fu', 'hu'], 'へ': ['he'], 'ほ': ['ho'],
  'ま': ['ma'], 'み': ['mi'], 'む': ['mu'], 'め': ['me'], 'も': ['mo'],
  'や': ['ya'], 'ゆ': ['yu'], 'よ': ['yo'],
  'ら': ['ra'], 'り': ['ri'], 'る': ['ru'], 'れ': ['re'], 'ろ': ['ro'],
  'わ': ['wa'], 'を': ['wo'], 'ん': ['nn', 'xn'],
  'が': ['ga'], 'ぎ': ['gi'], 'ぐ': ['gu'], 'げ': ['ge'], 'ご': ['go'],
  'ざ': ['za'], 'じ': ['ji', 'zi'], 'ず': ['zu'], 'ぜ': ['ze'], 'ぞ': ['zo'],
  'だ': ['da'], 'ぢ': ['di'], 'づ': ['du'], 'で': ['de'], 'ど': ['do'],
  'ば': ['ba'], 'び': ['bi'], 'ぶ': ['bu'], 'べ': ['be'], 'ぼ': ['bo'],
  'ぱ': ['pa'], 'ぴ': ['pi'], 'ぷ': ['pu'], 'ぺ': ['pe'], 'ぽ': ['po'],
  'きゃ': ['kya'], 'きゅ': ['kyu'], 'きょ': ['kyo'],
  'しゃ': ['sha', 'sya'], 'しゅ': ['shu', 'syu'], 'しょ': ['sho', 'syo'],
  'ちゃ': ['tya', 'cha', 'cya'], 'ちゅ': ['tyu', 'chu', 'cyu'], 'ちょ': ['tyo', 'cho', 'cyo'],
  'にゃ': ['nya'], 'にゅ': ['nyu'], 'にょ': ['nyo'],
  'ひゃ': ['hya'], 'ひゅ': ['hyu'], 'ひょ': ['hyo'],
  'みゃ': ['mya'], 'みゅ': ['myu'], 'みょ': ['myo'],
  'りゃ': ['rya'], 'りゅ': ['ryu'], 'りょ': ['ryo'],
  'ぎゃ': ['gya'], 'ぎゅ': ['gyu'], 'ぎょ': ['gyo'],
  'じゃ': ['ja', 'jya', 'zya'], 'じゅ': ['ju', 'jyu', 'zyu'], 'じょ': ['jo', 'jyo', 'zyo'],
  'びゃ': ['bya'], 'びゅ': ['byu'], 'びょ': ['byo'],
  'ぴゃ': ['pya'], 'ぴゅ': ['pyu'], 'ぴょ': ['pyo'],
  'ふぁ': ['fa'], 'ふぃ': ['fi'], 'ふぇ': ['fe'], 'ふぉ': ['fo'],
  'てぃ': ['thi'], 'でぃ': ['dhi'],
  'ー': ['-'],
  'っ': ['xtsu', 'xtu', 'ltsu', 'ltu'],
  'ぁ': ['xa', 'la'], 'ぃ': ['xi', 'li'], 'ぅ': ['xu', 'lu'], 'ぇ': ['xe', 'le'], 'ぉ': ['xo', 'lo'],
  'ゃ': ['xya', 'lya'], 'ゅ': ['xyu', 'lyu'], 'ょ': ['xyo', 'lyo'],
};

// 読み（かな）をトークン（判定単位）に分割する。
export const tokenizeWord = (reading: string): Token[] => {
  const tokens: Token[] = [];
  let i = 0;
  while (i < reading.length) {
    const char = reading[i];
    const nextChar = reading[i + 1] || '';
    if (ROMAJI_MAP[char + nextChar]) {
      tokens.push({ kana: char + nextChar, romaji: ROMAJI_MAP[char + nextChar] });
      i += 2;
    } else if (ROMAJI_MAP[char]) {
      tokens.push({ kana: char, romaji: ROMAJI_MAP[char] });
      i += 1;
    } else {
      tokens.push({ kana: char, romaji: [char] });
      i += 1;
    }
  }
  // 促音「っ」は次の音の頭の子音を重ねる表記をデフォルトにする（例: きって→t）。
  // xtu/ltu などの明示入力も引き続き許容する。
  tokens.forEach((tk, idx) => {
    if (tk.kana !== 'っ') return;
    const next = tokens[idx + 1];
    const c = next?.romaji[0]?.[0];
    if (c && !'aiueon'.includes(c)) {
      tk.romaji = [c, 'xtu', 'xtsu', 'ltu', 'ltsu'];
    }
  });
  return tokens;
};

// 単語IDの連番カウンタ（React の key 用。シードに依存せず常に一意）。
let idCounter = 0;

function buildWord(entry: WordEntry, type: WordType, prefix: string): Word {
  return {
    id: `${prefix}${idCounter++}`,
    display: entry.display,
    reading: entry.reading,
    type,
    tokens: tokenizeWord(entry.reading),
  };
}

// 与えられた決定論的 RNG から新しい単語を生成する。
// theme を指定すると、そのテーマ（タグ）の語彙からのみ出題する。
export const generateWord = (rng: RNG, theme: string = 'all'): Word => {
  const pool = THEME_POOLS[theme] ?? WORD_POOL;
  const entry = pool[Math.floor(rng() * pool.length)];
  const rand = rng();
  let type: WordType = 'normal';
  if (rand < 0.1) type = 'treasure'; // 10%でお宝
  else if (rand < 0.3) type = 'ojama'; // 20%でおじゃま
  return buildWord(entry, type, 'w');
};

// 受信したおじゃま用の単語（常に ojama）。攻撃由来なので Math.random で選ぶ。
export const makeOjamaWord = (): Word => {
  const entry = WORD_POOL[Math.floor(Math.random() * WORD_POOL.length)];
  return buildWord(entry, 'ojama', 'o');
};

// アイテム「ロング送信」で相手に送りつける長文（読みは14文字以上）。
// 1個でも打ち切るのに時間がかかる“重い”お邪魔として機能する。
// ロング送信（長文アイテム）専用の長文。読みは14文字以上の普通の文章。
// ことわざは「言い切り形」にして長文ではなくなったため、長文ジャンルからは外し、
// 専用の長文をここで生成して送る。
export const LONG_SENTENCES: WordEntry[] = [
  { display: '今日はとても良い天気で散歩日和だ', reading: 'きょうはとてもよいてんきでさんぽびよりだ' },
  { display: '図書館で借りた本を期限までに返す', reading: 'としょかんでかりたほんをきげんまでにかえす' },
  { display: '明日の会議の資料を今夜中に作る', reading: 'あしたのかいぎのしりょうをこんやじゅうにつくる' },
  { display: '週末は家族と一緒に映画を見に行く', reading: 'しゅうまつはかぞくといっしょにえいがをみにいく' },
  { display: '健康のために毎朝早起きして運動する', reading: 'けんこうのためにまいあさはやおきしてうんどうする' },
  { display: '電車が遅れたので約束に間に合わない', reading: 'でんしゃがおくれたのでやくそくにまにあわない' },
  { display: '夏休みの宿題を計画的に進めていく', reading: 'なつやすみのしゅくだいをけいかくてきにすすめていく' },
  { display: '雨が降りそうなので傘を持って出かける', reading: 'あめがふりそうなのでかさをもってでかける' },
  { display: '期末試験に向けて毎日少しずつ勉強する', reading: 'きまつしけんにむけてまいにちすこしずつべんきょうする' },
  { display: '友達と待ち合わせて買い物に出かけた', reading: 'ともだちとまちあわせてかいものにでかけた' },
  { display: '締め切りが近いので集中して仕上げる', reading: 'しめきりがちかいのでしゅうちゅうしてしあげる' },
  { display: '朝ごはんをしっかり食べて学校へ行く', reading: 'あさごはんをしっかりたべてがっこうへいく' },
  { display: '部屋を片付けてから友達を家に呼ぶ', reading: 'へやをかたづけてからともだちをいえによぶ' },
  { display: '新しい言葉を覚えるのは時間がかかる', reading: 'あたらしいことばをおぼえるのはじかんがかかる' },
  { display: '夕食の後に家族みんなで散歩をする', reading: 'ゆうしょくのあとにかぞくみんなでさんぽをする' },
  { display: '仕事の合間に温かいお茶で一息つく', reading: 'しごとのあいまにあたたかいおちゃでひといきつく' },
  { display: '週末の天気が良ければ山に登りたい', reading: 'しゅうまつのてんきがよければやまにのぼりたい' },
  { display: '自転車で通学する途中に猫を見かけた', reading: 'じてんしゃでつうがくするとちゅうにねこをみかけた' },
  { display: '引っ越しの準備で荷物をまとめている', reading: 'ひっこしのじゅんびでにもつをまとめている' },
  { display: '試合に勝つために毎日練習を続ける', reading: 'しあいにかつためにまいにちれんしゅうをつづける' },
  { display: '雪が積もったので朝早く雪かきをした', reading: 'ゆきがつもったのであさはやくゆきかきをした' },
  { display: '誕生日に欲しかった本を買ってもらう', reading: 'たんじょうびにほしかったほんをかってもらう' },
  { display: '庭に咲いた花に毎朝水をあげている', reading: 'にわにさいたはなにまいあさみずをあげている' },
  { display: '窓を開けて朝の涼しい風を入れる', reading: 'まどをあけてあさのすずしいかぜをいれる' },
  { display: '駅まで歩いて電車に乗り換える', reading: 'えきまであるいてでんしゃにのりかえる' },
  { display: '本屋で面白そうな小説を見つけた', reading: 'ほんやでおもしろそうなしょうせつをみつけた' },
  { display: '台所で夕飯の支度を急いでする', reading: 'だいどころでゆうはんのしたくをいそいでする' },
  { display: '紅茶に砂糖を入れてゆっくり飲む', reading: 'こうちゃにさとうをいれてゆっくりのむ' },
  { display: '朝市で新鮮な野菜をたくさん買った', reading: 'あさいちでしんせんなやさいをたくさんかった' },
  { display: '公園を散歩しながら音楽を聴いた', reading: 'こうえんをさんぽしながらおんがくをきいた' },
];

// ロング送信用の長文をランダムに選ぶ（表示と読みのペア）。
export const randomLongWord = (): { display: string; reading: string } => {
  const e = LONG_SENTENCES[Math.floor(Math.random() * LONG_SENTENCES.length)];
  return { display: e.display, reading: e.reading };
};

// 指定の表示・読みからおじゃま単語を生成（受信したロング送信の挿入用）。
export const makeOjamaWordFrom = (display: string, reading: string): Word => ({
  id: `o${idCounter++}`,
  display,
  reading,
  type: 'ojama',
  tokens: tokenizeWord(reading),
});

// --- 出題テーマ（タグ） ---
// 語彙をタグで分類し、テーマを選んで出題範囲を絞れるようにする。
export interface Theme {
  id: string;
  label: string;
}

// 通常出題は「単語のみ」。長文はロング送信アイテム専用にするためテーマには
// 含めない（LONG_SENTENCES は makeOjamaWordFrom 経由でのみ出現）。
export const THEMES: Theme[] = [
  { id: 'all', label: 'すべて' },
  { id: 'greeting', label: 'あいさつ' },
  { id: 'it', label: 'IT・ゲーム' },
  { id: 'food', label: '食べ物' },
  { id: 'nature', label: '自然・乗物' },
  { id: 'school', label: '学校・生活' },
];

// テーマごとの語彙プール。'all' は全語彙（WORD_POOL）を使う。
const THEME_POOLS: Record<string, WordEntry[]> = {
  greeting: [
    { display: 'ありがとう', reading: 'ありがとう' },
    { display: 'こんにちは', reading: 'こんにちは' },
    { display: '宜しく', reading: 'よろしく' },
    { display: '頑張って', reading: 'がんばって' },
    { display: 'お疲れ様', reading: 'おつかれさま' },
    { display: '初めまして', reading: 'はじめまして' },
    { display: 'おはよう', reading: 'おはよう' },
    { display: 'こんばんは', reading: 'こんばんは' },
    { display: 'さようなら', reading: 'さようなら' },
    { display: 'おやすみ', reading: 'おやすみ' },
    { display: 'ただいま', reading: 'ただいま' },
    { display: 'おかえり', reading: 'おかえり' },
    { display: '頂きます', reading: 'いただきます' },
    { display: 'ご馳走様', reading: 'ごちそうさま' },
    { display: 'すみません', reading: 'すみません' },
    { display: 'ごめんなさい', reading: 'ごめんなさい' },
    { display: 'お願いします', reading: 'おねがいします' },
    { display: '失礼します', reading: 'しつれいします' },
    { display: 'お元気ですか', reading: 'おげんきですか' },
    { display: '久しぶり', reading: 'ひさしぶり' },
    { display: 'おめでとう', reading: 'おめでとう' },
    { display: '行ってきます', reading: 'いってきます' },
    { display: '行ってらっしゃい', reading: 'いってらっしゃい' },
    { display: '大丈夫', reading: 'だいじょうぶ' },
    { display: '気を付けて', reading: 'きをつけて' },
    { display: 'また明日', reading: 'またあした' },
    { display: 'お先に', reading: 'おさきに' },
    { display: '助かります', reading: 'たすかります' },
    { display: '感謝', reading: 'かんしゃ' },
    { display: '乾杯', reading: 'かんぱい' },
    { display: 'いらっしゃい', reading: 'いらっしゃい' },
    { display: 'かしこまりました', reading: 'かしこまりました' },
    { display: '承知しました', reading: 'しょうちしました' },
    { display: '楽しかった', reading: 'たのしかった' },
    { display: '嬉しい', reading: 'うれしい' },
    { display: '頑張ろう', reading: 'がんばろう' },
    { display: '応援', reading: 'おうえん' },
    { display: 'お大事に', reading: 'おだいじに' },
    { display: 'ようこそ', reading: 'ようこそ' },
    { display: '始めよう', reading: 'はじめよう' },
    { display: 'ご機嫌よう', reading: 'ごきげんよう' },
    { display: 'おやすみなさい', reading: 'おやすみなさい' },
    { display: 'どうぞ', reading: 'どうぞ' },
    { display: '素敵だね', reading: 'すてきだね' },
    { display: 'なるほど', reading: 'なるほど' },
    { display: 'もちろん', reading: 'もちろん' },
    { display: '元気だよ', reading: 'げんきだよ' },
    { display: 'こちらこそ', reading: 'こちらこそ' },
    { display: 'お邪魔します', reading: 'おじゃまします' },
    { display: 'また会おう', reading: 'またあおう' },
  ],
  it: [
    { display: 'タイピング', reading: 'たいぴんぐ' },
    { display: 'キーボード', reading: 'きーぼーど' },
    { display: 'マウス', reading: 'まうす' },
    { display: 'パソコン', reading: 'ぱそこん' },
    { display: 'インターネット', reading: 'いんたーねっと' },
    { display: 'プログラミング', reading: 'ぷろぐらみんぐ' },
    { display: '技術者', reading: 'ぎじゅつしゃ' },
    { display: '開発', reading: 'かいはつ' },
    { display: '画面', reading: 'がめん' },
    { display: '通信', reading: 'つうしん' },
    { display: '対戦', reading: 'たいせん' },
    { display: '連鎖', reading: 'れんさ' },
    { display: '攻撃', reading: 'こうげき' },
    { display: '逆転', reading: 'ぎゃくてん' },
    { display: '勝利', reading: 'しょうり' },
    { display: 'ソフト', reading: 'そふと' },
    { display: 'ハード', reading: 'はーど' },
    { display: 'アプリ', reading: 'あぷり' },
    { display: 'データ', reading: 'でーた' },
    { display: 'ファイル', reading: 'ふぁいる' },
    { display: 'フォルダ', reading: 'ふぉるだ' },
    { display: 'サーバー', reading: 'さーばー' },
    { display: 'ネットワーク', reading: 'ねっとわーく' },
    { display: 'ログイン', reading: 'ろぐいん' },
    { display: 'パスワード', reading: 'ぱすわーど' },
    { display: 'ダウンロード', reading: 'だうんろーど' },
    { display: 'アップロード', reading: 'あっぷろーど' },
    { display: 'インストール', reading: 'いんすとーる' },
    { display: 'アップデート', reading: 'あっぷでーと' },
    { display: 'クリック', reading: 'くりっく' },
    { display: 'スクロール', reading: 'すくろーる' },
    { display: 'ブラウザ', reading: 'ぶらうざ' },
    { display: '検索', reading: 'けんさく' },
    { display: '画像', reading: 'がぞう' },
    { display: '動画', reading: 'どうが' },
    { display: '設定', reading: 'せってい' },
    { display: '保存', reading: 'ほぞん' },
    { display: '編集', reading: 'へんしゅう' },
    { display: '削除', reading: 'さくじょ' },
    { display: '入力', reading: 'にゅうりょく' },
    { display: '出力', reading: 'しゅつりょく' },
    { display: '変数', reading: 'へんすう' },
    { display: '関数', reading: 'かんすう' },
    { display: '配列', reading: 'はいれつ' },
    { display: '条件分岐', reading: 'じょうけんぶんき' },
    { display: '繰り返し', reading: 'くりかえし' },
    { display: '実行', reading: 'じっこう' },
    { display: '暗号化', reading: 'あんごうか' },
    { display: '再起動', reading: 'さいきどう' },
    { display: '接続', reading: 'せつぞく' },
    { display: '必殺技', reading: 'ひっさつわざ' },
    { display: '連勝', reading: 'れんしょう' },
  ],
  food: [
    { display: 'お握り', reading: 'おにぎり' },
    { display: 'ハンバーガー', reading: 'はんばーがー' },
    { display: '拉麺', reading: 'らーめん' },
    { display: '林檎', reading: 'りんご' },
    { display: '蜜柑', reading: 'みかん' },
    { display: '西瓜', reading: 'すいか' },
    { display: '寿司', reading: 'すし' },
    { display: '味噌汁', reading: 'みそしる' },
    { display: '玉子焼き', reading: 'たまごやき' },
    { display: '珈琲', reading: 'こーひー' },
    { display: 'カレー', reading: 'かれー' },
    { display: 'うどん', reading: 'うどん' },
    { display: '蕎麦', reading: 'そば' },
    { display: '焼き鳥', reading: 'やきとり' },
    { display: '唐揚げ', reading: 'からあげ' },
    { display: '餃子', reading: 'ぎょうざ' },
    { display: '天ぷら', reading: 'てんぷら' },
    { display: '刺身', reading: 'さしみ' },
    { display: '牛丼', reading: 'ぎゅうどん' },
    { display: '親子丼', reading: 'おやこどん' },
    { display: 'お好み焼き', reading: 'おこのみやき' },
    { display: 'たこ焼き', reading: 'たこやき' },
    { display: '焼きそば', reading: 'やきそば' },
    { display: '団子', reading: 'だんご' },
    { display: '大福', reading: 'だいふく' },
    { display: '羊羹', reading: 'ようかん' },
    { display: '煎餅', reading: 'せんべい' },
    { display: '苺', reading: 'いちご' },
    { display: '葡萄', reading: 'ぶどう' },
    { display: '桃', reading: 'もも' },
    { display: '梨', reading: 'なし' },
    { display: '柿', reading: 'かき' },
    { display: 'バナナ', reading: 'ばなな' },
    { display: 'メロン', reading: 'めろん' },
    { display: '人参', reading: 'にんじん' },
    { display: '玉葱', reading: 'たまねぎ' },
    { display: '馬鈴薯', reading: 'じゃがいも' },
    { display: '南瓜', reading: 'かぼちゃ' },
    { display: '茄子', reading: 'なす' },
    { display: '胡瓜', reading: 'きゅうり' },
    { display: '卵', reading: 'たまご' },
    { display: '牛乳', reading: 'ぎゅうにゅう' },
    { display: '紅茶', reading: 'こうちゃ' },
    { display: '緑茶', reading: 'りょくちゃ' },
    { display: '炭酸水', reading: 'たんさんすい' },
    { display: '砂糖', reading: 'さとう' },
    { display: '胡椒', reading: 'こしょう' },
    { display: '弁当', reading: 'べんとう' },
    { display: '朝食', reading: 'ちょうしょく' },
    { display: '夕食', reading: 'ゆうしょく' },
    { display: '食欲', reading: 'しょくよく' },
  ],
  nature: [
    { display: '太陽', reading: 'たいよう' },
    { display: '宇宙', reading: 'うちゅう' },
    { display: '青空', reading: 'あおぞら' },
    { display: '新幹線', reading: 'しんかんせん' },
    { display: '飛行機', reading: 'ひこうき' },
    { display: '自転車', reading: 'じてんしゃ' },
    { display: '電車', reading: 'でんしゃ' },
    { display: '海', reading: 'うみ' },
    { display: '山', reading: 'やま' },
    { display: '川', reading: 'かわ' },
    { display: '森林', reading: 'しんりん' },
    { display: '稲妻', reading: 'いなずま' },
    { display: '月', reading: 'つき' },
    { display: '星', reading: 'ほし' },
    { display: '雲', reading: 'くも' },
    { display: '雨', reading: 'あめ' },
    { display: '雪', reading: 'ゆき' },
    { display: '風', reading: 'かぜ' },
    { display: '雷', reading: 'かみなり' },
    { display: '虹', reading: 'にじ' },
    { display: '台風', reading: 'たいふう' },
    { display: '地震', reading: 'じしん' },
    { display: '火山', reading: 'かざん' },
    { display: '砂漠', reading: 'さばく' },
    { display: '湖', reading: 'みずうみ' },
    { display: '滝', reading: 'たき' },
    { display: '島', reading: 'しま' },
    { display: '銀河', reading: 'ぎんが' },
    { display: '惑星', reading: 'わくせい' },
    { display: '彗星', reading: 'すいせい' },
    { display: '衛星', reading: 'えいせい' },
    { display: '草原', reading: 'そうげん' },
    { display: '紅葉', reading: 'こうよう' },
    { display: '桜', reading: 'さくら' },
    { display: '自動車', reading: 'じどうしゃ' },
    { display: 'バス', reading: 'ばす' },
    { display: 'タクシー', reading: 'たくしー' },
    { display: '地下鉄', reading: 'ちかてつ' },
    { display: '船', reading: 'ふね' },
    { display: '客船', reading: 'きゃくせん' },
    { display: 'ロケット', reading: 'ろけっと' },
    { display: '気球', reading: 'ききゅう' },
    { display: '救急車', reading: 'きゅうきゅうしゃ' },
    { display: '消防車', reading: 'しょうぼうしゃ' },
    { display: '路面電車', reading: 'ろめんでんしゃ' },
    { display: '貨物列車', reading: 'かもつれっしゃ' },
    { display: '高速道路', reading: 'こうそくどうろ' },
    { display: '信号機', reading: 'しんごうき' },
    { display: '踏切', reading: 'ふみきり' },
    { display: '渡り鳥', reading: 'わたりどり' },
  ],
  school: [
    { display: '小学校', reading: 'しょうがっこう' },
    { display: '大学', reading: 'だいがく' },
    { display: '図書館', reading: 'としょかん' },
    { display: '宿題', reading: 'しゅくだい' },
    { display: '友達', reading: 'ともだち' },
    { display: '家族', reading: 'かぞく' },
    { display: '音楽', reading: 'おんがく' },
    { display: '映画', reading: 'えいが' },
    { display: '物語', reading: 'ものがたり' },
    { display: '挑戦', reading: 'ちょうせん' },
    { display: '冒険', reading: 'ぼうけん' },
    { display: '出発', reading: 'しゅっぱつ' },
    { display: '集中', reading: 'しゅうちゅう' },
    { display: '中学校', reading: 'ちゅうがっこう' },
    { display: '高校', reading: 'こうこう' },
    { display: '教室', reading: 'きょうしつ' },
    { display: '黒板', reading: 'こくばん' },
    { display: '先生', reading: 'せんせい' },
    { display: '生徒', reading: 'せいと' },
    { display: '授業', reading: 'じゅぎょう' },
    { display: '試験', reading: 'しけん' },
    { display: '成績', reading: 'せいせき' },
    { display: '部活', reading: 'ぶかつ' },
    { display: '文化祭', reading: 'ぶんかさい' },
    { display: '運動会', reading: 'うんどうかい' },
    { display: '修学旅行', reading: 'しゅうがくりょこう' },
    { display: '給食', reading: 'きゅうしょく' },
    { display: '通学路', reading: 'つうがくろ' },
    { display: '教科書', reading: 'きょうかしょ' },
    { display: '鉛筆', reading: 'えんぴつ' },
    { display: '消しゴム', reading: 'けしごむ' },
    { display: '定規', reading: 'じょうぎ' },
    { display: '体育館', reading: 'たいいくかん' },
    { display: '委員長', reading: 'いいんちょう' },
    { display: '遅刻', reading: 'ちこく' },
    { display: '出席', reading: 'しゅっせき' },
    { display: '卒業式', reading: 'そつぎょうしき' },
    { display: '入学式', reading: 'にゅうがくしき' },
    { display: '制服', reading: 'せいふく' },
    { display: '部屋', reading: 'へや' },
    { display: '台所', reading: 'だいどころ' },
    { display: '玄関', reading: 'げんかん' },
    { display: '洗濯', reading: 'せんたく' },
    { display: '掃除', reading: 'そうじ' },
    { display: '料理', reading: 'りょうり' },
    { display: '買い物', reading: 'かいもの' },
    { display: '散歩', reading: 'さんぽ' },
    { display: '仕事', reading: 'しごと' },
    { display: '休日', reading: 'きゅうじつ' },
    { display: '趣味', reading: 'しゅみ' },
    { display: '健康', reading: 'けんこう' },
    { display: '約束', reading: 'やくそく' },
    { display: '節約', reading: 'せつやく' },
  ],
};
