import type { RNG } from './rng';
import type { Token, Word, WordType } from './types';

// お題の語彙。display=表示（漢字交じり）, reading=読み（かな・判定の元）。
interface WordEntry {
  display: string;
  reading: string;
}

export const WORD_POOL: WordEntry[] = [
  // あいさつ・日常
  { display: 'ありがとう', reading: 'ありがとう' },
  { display: 'こんにちは', reading: 'こんにちは' },
  { display: '宜しく', reading: 'よろしく' },
  { display: '頑張って', reading: 'がんばって' },
  { display: 'お疲れ様', reading: 'おつかれさま' },
  { display: '初めまして', reading: 'はじめまして' },
  // IT・ゲーム
  { display: 'タイピング', reading: 'たいぴんぐ' },
  { display: 'キーボード', reading: 'きーぼーど' },
  { display: 'マウス', reading: 'まうす' },
  { display: 'パソコン', reading: 'ぱそこん' },
  { display: 'インターネット', reading: 'いんたーねっと' },
  { display: 'プログラミング', reading: 'ぷろぐらみんぐ' },
  { display: '技術者', reading: 'ぎじゅつしゃ' },
  { display: '開発', reading: 'かいはつ' },
  { display: '画面', reading: 'がめん' },
  { display: '電源', reading: 'でんげん' },
  { display: '通信', reading: 'つうしん' },
  { display: '対戦', reading: 'たいせん' },
  { display: '連鎖', reading: 'れんさ' },
  { display: '攻撃', reading: 'こうげき' },
  { display: '逆転', reading: 'ぎゃくてん' },
  { display: '勝利', reading: 'しょうり' },
  { display: '宝物', reading: 'たからもの' },
  { display: '道具', reading: 'どうぐ' },
  // 食べ物
  { display: 'お握り', reading: 'おにぎり' },
  { display: 'ハンバーガー', reading: 'はんばーがー' },
  { display: '拉麺', reading: 'らーめん' },
  { display: '林檎', reading: 'りんご' },
  { display: '蜜柑', reading: 'みかん' },
  { display: '西瓜', reading: 'すいか' },
  { display: '寿司', reading: 'すし' },
  { display: '味噌汁', reading: 'みそしる' },
  { display: '玉子焼き', reading: 'たまごやき' },
  { display: '珈琲', reading: 'こーひー' },
  // 自然・乗り物
  { display: '太陽', reading: 'たいよう' },
  { display: '宇宙', reading: 'うちゅう' },
  { display: '青空', reading: 'あおぞら' },
  { display: '新幹線', reading: 'しんかんせん' },
  { display: '飛行機', reading: 'ひこうき' },
  { display: '自転車', reading: 'じてんしゃ' },
  { display: '電車', reading: 'でんしゃ' },
  { display: '海', reading: 'うみ' },
  { display: '山', reading: 'やま' },
  { display: '川', reading: 'かわ' },
  { display: '森林', reading: 'しんりん' },
  { display: '稲妻', reading: 'いなずま' },
  // 学校・生活
  { display: '小学校', reading: 'しょうがっこう' },
  { display: '大学', reading: 'だいがく' },
  { display: '図書館', reading: 'としょかん' },
  { display: '宿題', reading: 'しゅくだい' },
  { display: '友達', reading: 'ともだち' },
  { display: '家族', reading: 'かぞく' },
  { display: '音楽', reading: 'おんがく' },
  { display: '映画', reading: 'えいが' },
  { display: '物語', reading: 'ものがたり' },
  { display: '挑戦', reading: 'ちょうせん' },
  { display: '冒険', reading: 'ぼうけん' },
  { display: '出発', reading: 'しゅっぱつ' },
  { display: '一番', reading: 'いちばん' },
  { display: '全力', reading: 'ぜんりょく' },
  { display: '集中', reading: 'しゅうちゅう' },
  { display: '反撃', reading: 'はんげき' },
  { display: '相殺', reading: 'そうさい' },
  // 追加語彙
  { display: '人懐っこい', reading: 'ひとなつっこい' },
  { display: '熱放射', reading: 'ねつほうしゃ' },
  { display: '貿易', reading: 'ぼうえき' },
  { display: 'クラクション', reading: 'くらくしょん' },
  { display: '掛け軸', reading: 'かけじく' },
  { display: '人混み', reading: 'ひとごみ' },
  { display: '調理実習', reading: 'ちょうりじっしゅう' },
  { display: '横顔', reading: 'よこがお' },
  { display: '受験勉強', reading: 'じゅけんべんきょう' },
  { display: 'クリスタル', reading: 'くりすたる' },
  { display: '醤油', reading: 'しょうゆ' },
  { display: '回文', reading: 'かいぶん' },
  { display: 'どん底', reading: 'どんぞこ' },
  { display: '有権者', reading: 'ゆうけんしゃ' },
  { display: '鼻毛', reading: 'はなげ' },
  { display: '赤目', reading: 'あかめ' },
  { display: '月曜日', reading: 'げつようび' },
  { display: '倒置法', reading: 'とうちほう' },
  { display: 'ネットゲーム', reading: 'ねっとげーむ' },
  { display: 'グリーンピース', reading: 'ぐりーんぴーす' },
  { display: 'カモノハシ', reading: 'かものはし' },
  { display: 'かみなり雲', reading: 'かみなりぐも' },
  { display: '問題解決', reading: 'もんだいかいけつ' },
  { display: 'スポンサー', reading: 'すぽんさー' },
  { display: '戦闘服', reading: 'せんとうふく' },
  { display: '湿る', reading: 'しめる' },
  { display: '乱発', reading: 'らんぱつ' },
  { display: '原材料', reading: 'げんざいりょう' },
  { display: '路線変更', reading: 'ろせんへんこう' },
  { display: '遠足', reading: 'えんそく' },
  { display: 'ホットココア', reading: 'ほっとここあ' },
  { display: '少女漫画', reading: 'しょうじょまんが' },
  { display: '洞察力', reading: 'どうさつりょく' },
  { display: '出演', reading: 'しゅつえん' },
  { display: '昆虫標本', reading: 'こんちゅうひょうほん' },
  { display: '充電', reading: 'じゅうでん' },
  { display: 'トレーニング', reading: 'とれーにんぐ' },
  { display: '両思い', reading: 'りょうおもい' },
  { display: '卒業アルバム', reading: 'そつぎょうあるばむ' },
  { display: 'コンビニスイーツ', reading: 'こんびにすいーつ' },
  { display: '懸賞金', reading: 'けんしょうきん' },
  { display: '外来種', reading: 'がいらいしゅ' },
  { display: 'メリーゴーランド', reading: 'めりーごーらんど' },
  { display: 'かりあげ', reading: 'かりあげ' },
  { display: 'サラリーマン', reading: 'さらりーまん' },
  { display: 'まばら', reading: 'まばら' },
  { display: '聴診器', reading: 'ちょうしんき' },
  { display: '玉虫色', reading: 'たまむしいろ' },
  { display: '有刺鉄線', reading: 'ゆうしてっせん' },
  // 追加語彙 2
  { display: '焼きそばパン', reading: 'やきそばぱん' },
  { display: '変わらない', reading: 'かわらない' },
  { display: '通販サイト', reading: 'つうはんさいと' },
  { display: '一握り', reading: 'ひとにぎり' },
  { display: '送料無料', reading: 'そうりょうむりょう' },
  { display: '誕生石', reading: 'たんじょうせき' },
  { display: 'だきまくら', reading: 'だきまくら' },
  { display: 'お笑いコンビ', reading: 'おわらいこんび' },
  { display: '殿堂入り', reading: 'でんどういり' },
  { display: '大騒ぎ', reading: 'おおさわぎ' },
  { display: '司会者', reading: 'しかいしゃ' },
  { display: '予想通り', reading: 'よそうどおり' },
  { display: '音楽番組', reading: 'おんがくばんぐみ' },
  { display: '機種変更', reading: 'きしゅへんこう' },
  { display: 'ナルト', reading: 'なると' },
  { display: 'あられ', reading: 'あられ' },
  { display: 'お祓い', reading: 'おはらい' },
  { display: 'ゲーム機', reading: 'げーむき' },
  { display: '江戸時代', reading: 'えどじだい' },
  { display: 'トラベラー', reading: 'とらべらー' },
  { display: '正義は勝つ', reading: 'せいぎはかつ' },
  { display: '保証金', reading: 'ほしょうきん' },
  { display: 'ホラー漫画', reading: 'ほらーまんが' },
  { display: '準決勝', reading: 'じゅんけっしょう' },
  { display: 'ショートケーキ', reading: 'しょーとけーき' },
  { display: 'ヨーロッパ', reading: 'よーろっぱ' },
  { display: '二十面相', reading: 'にじゅうめんそう' },
  { display: 'パズルゲーム', reading: 'ぱずるげーむ' },
  { display: '日本地図', reading: 'にほんちず' },
  { display: '生卵', reading: 'なまたまご' },
  { display: '朝方', reading: 'あさがた' },
  { display: '囁く', reading: 'ささやく' },
  { display: '呼吸法', reading: 'こきゅうほう' },
  { display: 'シャボン玉', reading: 'しゃぼんだま' },
  { display: '哺乳類', reading: 'ほにゅうるい' },
  { display: 'イノベーション', reading: 'いのべーしょん' },
  { display: 'コンディショナー', reading: 'こんでぃしょなー' },
  { display: '現行犯', reading: 'げんこうはん' },
  { display: '競馬', reading: 'けいば' },
  { display: 'キャンセル料', reading: 'きゃんせるりょう' },
  { display: '爪痕', reading: 'つめあと' },
  { display: '大使', reading: 'たいし' },
  { display: '数学', reading: 'すうがく' },
  { display: 'もやし', reading: 'もやし' },
  { display: '百万年後', reading: 'ひゃくまんねんご' },
  { display: '老人ホーム', reading: 'ろうじんほーむ' },
  { display: '世代交代', reading: 'せだいこうたい' },
  { display: '繰り返す', reading: 'くりかえす' },
  { display: '優勝カップ', reading: 'ゆうしょうかっぷ' },
  { display: 'バーテンダー', reading: 'ばーてんだー' },
  // 追加語彙 3
  { display: '二階から目薬', reading: 'にかいからめぐすり' },
  { display: 'クレーター', reading: 'くれーたー' },
  { display: '心の目', reading: 'こころのめ' },
  { display: '朝寝坊', reading: 'あさねぼう' },
  { display: '影絵', reading: 'かげえ' },
  { display: '裏切り', reading: 'うらぎり' },
  { display: '羊', reading: 'ひつじ' },
  { display: '高級車', reading: 'こうきゅうしゃ' },
  { display: 'ホールインワン', reading: 'ほーるいんわん' },
  { display: '化学反応', reading: 'かがくはんのう' },
  { display: '繰り出す', reading: 'くりだす' },
  { display: '直談判', reading: 'じかだんぱん' },
  { display: '小学生', reading: 'しょうがくせい' },
  { display: '百発百中', reading: 'ひゃっぱつひゃくちゅう' },
  { display: '幸か不幸か', reading: 'こうかふこうか' },
  { display: 'ヘアアイロン', reading: 'へああいろん' },
  { display: '挙動不審', reading: 'きょどうふしん' },
  { display: 'シークワーサー', reading: 'しーくわーさー' },
  { display: '無', reading: 'む' },
  { display: 'コンビニエンスストア', reading: 'こんびにえんすすとあ' },
  { display: '急転直下', reading: 'きゅうてんちょっか' },
  { display: '晴れ', reading: 'はれ' },
  { display: '写真週刊誌', reading: 'しゃしんしゅうかんし' },
  { display: '十進法', reading: 'じっしんほう' },
  { display: '弁当箱', reading: 'べんとうばこ' },
  { display: '無人駅', reading: 'むじんえき' },
  { display: '運転手', reading: 'うんてんしゅ' },
  { display: 'お布団', reading: 'おふとん' },
  { display: '保健室', reading: 'ほけんしつ' },
  { display: '誤解', reading: 'ごかい' },
  { display: '花吹雪', reading: 'はなふぶき' },
  { display: '間一髪', reading: 'かんいっぱつ' },
  { display: '草食系男子', reading: 'そうしょくけいだんし' },
  { display: '神がかり', reading: 'かみがかり' },
  { display: '国語', reading: 'こくご' },
  { display: 'ぼたもち', reading: 'ぼたもち' },
  { display: '放送事故', reading: 'ほうそうじこ' },
  { display: '進捗を生む', reading: 'しんちょくをうむ' },
  { display: '皮', reading: 'かわ' },
  { display: '昼下がり', reading: 'ひるさがり' },
  { display: '言葉遣い', reading: 'ことばづかい' },
  { display: '河原', reading: 'かわら' },
  { display: '挨拶代わり', reading: 'あいさつがわり' },
  { display: 'ホットミルク', reading: 'ほっとみるく' },
  { display: '奇妙', reading: 'きみょう' },
  { display: 'フンコロガシ', reading: 'ふんころがし' },
  { display: 'ピストル', reading: 'ぴすとる' },
  { display: 'アイマスク', reading: 'あいますく' },
  // 追加語彙 4
  { display: '腕時計', reading: 'うでどけい' },
  { display: '観覧車', reading: 'かんらんしゃ' },
  { display: '時間割', reading: 'じかんわり' },
  { display: '万華鏡', reading: 'まんげきょう' },
  { display: '雑誌', reading: 'ざっし' },
  { display: '新聞紙', reading: 'しんぶんし' },
  { display: '消防士', reading: 'しょうぼうし' },
  { display: '看護師', reading: 'かんごし' },
  { display: '美容院', reading: 'びよういん' },
  { display: '歯医者', reading: 'はいしゃ' },
  { display: '郵便局', reading: 'ゆうびんきょく' },
  { display: '交差点', reading: 'こうさてん' },
  { display: '横断歩道', reading: 'おうだんほどう' },
  { display: '駐車場', reading: 'ちゅうしゃじょう' },
  { display: '自動販売機', reading: 'じどうはんばいき' },
  { display: '観光地', reading: 'かんこうち' },
  { display: '温泉旅行', reading: 'おんせんりょこう' },
  { display: '記念撮影', reading: 'きねんさつえい' },
  { display: '花火大会', reading: 'はなびたいかい' },
  { display: '夏祭り', reading: 'なつまつり' },
  { display: '冬将軍', reading: 'ふゆしょうぐん' },
  { display: '木枯らし', reading: 'こがらし' },
  { display: '紅葉狩り', reading: 'もみじがり' },
  { display: '雪だるま', reading: 'ゆきだるま' },
  { display: '鏡餅', reading: 'かがみもち' },
  { display: '初詣', reading: 'はつもうで' },
  { display: '門松', reading: 'かどまつ' },
  { display: '年賀状', reading: 'ねんがじょう' },
  { display: '走馬灯', reading: 'そうまとう' },
  { display: '提灯', reading: 'ちょうちん' },
  { display: '風鈴', reading: 'ふうりん' },
  { display: '扇風機', reading: 'せんぷうき' },
  { display: '麦茶', reading: 'むぎちゃ' },
  { display: '蚊取り線香', reading: 'かとりせんこう' },
  { display: '冷蔵庫', reading: 'れいぞうこ' },
  { display: '洗濯機', reading: 'せんたくき' },
  { display: '掃除機', reading: 'そうじき' },
  { display: '目覚まし時計', reading: 'めざましどけい' },
  { display: '懐中電灯', reading: 'かいちゅうでんとう' },
  { display: '双眼鏡', reading: 'そうがんきょう' },
  { display: '顕微鏡', reading: 'けんびきょう' },
  { display: '天体望遠鏡', reading: 'てんたいぼうえんきょう' },
  { display: '実験器具', reading: 'じっけんきぐ' },
  { display: '化石発掘', reading: 'かせきはっくつ' },
  { display: '恐竜時代', reading: 'きょうりゅうじだい' },
  { display: '深海魚', reading: 'しんかいぎょ' },
  { display: '北極星', reading: 'ほっきょくせい' },
  { display: '流れ星', reading: 'ながれぼし' },
  { display: '三日月', reading: 'みかづき' },
  { display: '満月', reading: 'まんげつ' },
  { display: '日食', reading: 'にっしょく' },
  { display: '潮干狩り', reading: 'しおひがり' },
  { display: '砂時計', reading: 'すなどけい' },
  { display: '羅針盤', reading: 'らしんばん' },
  { display: '宝の地図', reading: 'たからのちず' },
  { display: '冒険者', reading: 'ぼうけんしゃ' },
  { display: '迷路', reading: 'めいろ' },
  { display: '謎解き', reading: 'なぞとき' },
  { display: '暗号', reading: 'あんごう' },
  { display: '合言葉', reading: 'あいことば' },
  { display: '秘密基地', reading: 'ひみつきち' },
  { display: '隠れ家', reading: 'かくれが' },
  { display: '屋根裏部屋', reading: 'やねうらべや' },
  { display: '展望台', reading: 'てんぼうだい' },
  { display: '吊り橋', reading: 'つりばし' },
  { display: '滑り台', reading: 'すべりだい' },
  { display: '砂場', reading: 'すなば' },
  { display: '鉄棒', reading: 'てつぼう' },
  { display: '一輪車', reading: 'いちりんしゃ' },
  { display: '竹馬', reading: 'たけうま' },
  { display: '折り紙', reading: 'おりがみ' },
  { display: '紙飛行機', reading: 'かみひこうき' },
  { display: '凧揚げ', reading: 'たこあげ' },
  { display: '影踏み', reading: 'かげふみ' },
  { display: '鬼ごっこ', reading: 'おにごっこ' },
  { display: '宝探し', reading: 'たからさがし' },
  { display: '探検隊', reading: 'たんけんたい' },
  { display: '集合写真', reading: 'しゅうごうしゃしん' },
  { display: '優先順位', reading: 'ゆうせんじゅんい' },
  { display: '臨機応変', reading: 'りんきおうへん' },
  { display: '一石二鳥', reading: 'いっせきにちょう' },
  { display: '十人十色', reading: 'じゅうにんといろ' },
  { display: '七転八起', reading: 'しちてんはっき' },
  { display: '電光石火', reading: 'でんこうせっか' },
  { display: '完全燃焼', reading: 'かんぜんねんしょう' },
  { display: '油断大敵', reading: 'ゆだんたいてき' },
  { display: '一期一会', reading: 'いちごいちえ' },
  { display: '不言実行', reading: 'ふげんじっこう' },
];

// ローマ字入力マッピング（柔軟な入力に対応）
export const ROMAJI_MAP: Record<string, string[]> = {
  'あ': ['a'], 'い': ['i'], 'う': ['u', 'wu'], 'え': ['e'], 'お': ['o'],
  'か': ['ka', 'ca'], 'き': ['ki'], 'く': ['ku', 'cu', 'qu'], 'け': ['ke'], 'こ': ['ko', 'co'],
  'さ': ['sa'], 'し': ['shi', 'si', 'ci'], 'す': ['su'], 'せ': ['se', 'ce'], 'そ': ['so'],
  'た': ['ta'], 'ち': ['chi', 'ti'], 'つ': ['tsu', 'tu'], 'て': ['te'], 'と': ['to'],
  'な': ['na'], 'に': ['ni'], 'ぬ': ['nu'], 'ね': ['ne'], 'の': ['no'],
  'は': ['ha'], 'ひ': ['hi'], 'ふ': ['fu', 'hu'], 'へ': ['he'], 'ほ': ['ho'],
  'ま': ['ma'], 'み': ['mi'], 'む': ['mu'], 'め': ['me'], 'も': ['mo'],
  'や': ['ya'], 'ゆ': ['yu'], 'よ': ['yo'],
  'ら': ['ra'], 'り': ['ri'], 'る': ['ru'], 'れ': ['re'], 'ろ': ['ro'],
  'わ': ['wa'], 'を': ['wo'], 'ん': ['nn', 'xn'],
  'が': ['ga'], 'ぎ': ['gi'], 'ぐ': ['gu'], 'げ': ['ge'], 'ご': ['go'],
  'ざ': ['za'], 'じ': ['ji', 'zi'], 'ず': ['zu'], 'ぜ': ['ze'], 'ぞ': ['zo'],
  'だ': ['da'], 'ぢ': ['di'], 'づ': ['du'], 'で': ['de'], 'ど': ['do'],
  'ば': ['ba'], 'び': ['bi'], 'ぶ': ['bu'], 'べ': ['be'], 'ぼ': ['bo'],
  'ぱ': ['pa'], 'ぴ': ['pi'], 'ぷ': ['pu'], 'ぺ': ['pe'], 'ぽ': ['po'],
  'きゃ': ['kya'], 'きゅ': ['kyu'], 'きょ': ['kyo'],
  'しゃ': ['sha', 'sya'], 'しゅ': ['shu', 'syu'], 'しょ': ['sho', 'syo'],
  'ちゃ': ['tya', 'cha', 'cya'], 'ちゅ': ['tyu', 'chu', 'cyu'], 'ちょ': ['tyo', 'cho', 'cyo'],
  'にゃ': ['nya'], 'にゅ': ['nyu'], 'にょ': ['nyo'],
  'ひゃ': ['hya'], 'ひゅ': ['hyu'], 'ひょ': ['hyo'],
  'みゃ': ['mya'], 'みゅ': ['myu'], 'みょ': ['myo'],
  'りゃ': ['rya'], 'りゅ': ['ryu'], 'りょ': ['ryo'],
  'ぎゃ': ['gya'], 'ぎゅ': ['gyu'], 'ぎょ': ['gyo'],
  'じゃ': ['ja', 'jya', 'zya'], 'じゅ': ['ju', 'jyu', 'zyu'], 'じょ': ['jo', 'jyo', 'zyo'],
  'びゃ': ['bya'], 'びゅ': ['byu'], 'びょ': ['byo'],
  'ぴゃ': ['pya'], 'ぴゅ': ['pyu'], 'ぴょ': ['pyo'],
  // 小さい母音を含む合成音は、合成綴り(fa など)に加えて
  // 「基音＋小さい母音(la/xa 系)」での分割入力も許容する。
  'ふぁ': ['fa', 'fula', 'fuxa', 'hula', 'huxa'],
  'ふぃ': ['fi', 'fuli', 'fuxi', 'huli', 'huxi'],
  'ふぇ': ['fe', 'fule', 'fuxe', 'hule', 'huxe'],
  'ふぉ': ['fo', 'fulo', 'fuxo', 'hulo', 'huxo'],
  'てぃ': ['thi', 'teli', 'texi'],
  'でぃ': ['dhi', 'deli', 'dexi'],
  'うぁ': ['wha', 'ula', 'uxa'], 'うぃ': ['wi', 'whi', 'uli', 'uxi'],
  'うぇ': ['we', 'whe', 'ule', 'uxe'], 'うぉ': ['who', 'ulo', 'uxo'],
  'ゔぁ': ['va', 'vula', 'vuxa'], 'ゔぃ': ['vi', 'vuli', 'vuxi'],
  'ゔぇ': ['ve', 'vule', 'vuxe'], 'ゔぉ': ['vo', 'vulo', 'vuxo'],
  'ー': ['-'],
  'っ': ['xtsu', 'xtu', 'ltsu', 'ltu'],
  'ぁ': ['xa', 'la'], 'ぃ': ['xi', 'li'], 'ぅ': ['xu', 'lu'], 'ぇ': ['xe', 'le'], 'ぉ': ['xo', 'lo'],
  'ゃ': ['xya', 'lya'], 'ゅ': ['xyu', 'lyu'], 'ょ': ['xyo', 'lyo'],
};

// 読み（かな）をトークン（判定単位）に分割する。
export const tokenizeWord = (reading: string): Token[] => {
  const tokens: Token[] = [];
  let i = 0;
  while (i < reading.length) {
    const char = reading[i];
    const nextChar = reading[i + 1] || '';
    if (ROMAJI_MAP[char + nextChar]) {
      tokens.push({ kana: char + nextChar, romaji: ROMAJI_MAP[char + nextChar] });
      i += 2;
    } else if (ROMAJI_MAP[char]) {
      tokens.push({ kana: char, romaji: ROMAJI_MAP[char] });
      i += 1;
    } else {
      tokens.push({ kana: char, romaji: [char] });
      i += 1;
    }
  }
  // 促音「っ」は次の音の頭の子音を重ねる表記をデフォルトにする（例: きって→t）。
  // xtu/ltu などの明示入力も引き続き許容する。
  tokens.forEach((tk, idx) => {
    if (tk.kana !== 'っ') return;
    const next = tokens[idx + 1];
    const c = next?.romaji[0]?.[0];
    if (c && !'aiueon'.includes(c)) {
      tk.romaji = [c, 'xtu', 'xtsu', 'ltu', 'ltsu'];
    }
  });
  return tokens;
};

// --- 振り仮名（ルビ）セグメント生成 ---
// 漢字部分にだけ振り仮名を付けるため、display を「漢字ラン / かな・記号ラン」に分け、
// reading を手がかりに各漢字ランの読みを切り出す。
export interface RubySeg {
  text: string;
  rt?: string; // 漢字ランのみ読みを持つ
}

// CJK 漢字（＋反復記号など）か判定する。
const isKanjiChar = (ch: string): boolean => {
  const c = ch.codePointAt(0) ?? 0;
  return (
    (c >= 0x4e00 && c <= 0x9fff) || // CJK統合漢字
    (c >= 0x3400 && c <= 0x4dbf) || // 拡張A
    ch === '々' ||
    ch === '〆' ||
    ch === 'ヶ' ||
    ch === 'ヵ'
  );
};

// カタカナ→ひらがな（reading[ひらがな]と照合するため）。
const kataToHira = (s: string): string =>
  s.replace(/[ァ-ヶ]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0x60));

// display と reading から、漢字部分にだけ rt（振り仮名）を付けたセグメント列を返す。
// ひらがな・カタカナ・記号には rt を付けない。
export function buildRuby(display: string, reading: string): RubySeg[] {
  // 同種文字（漢字 / 非漢字）が続く範囲をランにまとめる。
  const runs: { text: string; kanji: boolean }[] = [];
  for (const ch of display) {
    const kanji = isKanjiChar(ch);
    const last = runs[runs.length - 1];
    if (last && last.kanji === kanji) last.text += ch;
    else runs.push({ text: ch, kanji });
  }

  const segs: RubySeg[] = [];
  let ri = 0; // reading 内のポインタ
  for (let i = 0; i < runs.length; i++) {
    const run = runs[i];
    if (!run.kanji) {
      // かな/記号ランは reading 上をそのまま進める（カタカナはひらがな化して照合）。
      const hira = kataToHira(run.text);
      if (reading.startsWith(hira, ri)) ri += hira.length;
      segs.push({ text: run.text });
    } else {
      // 次のかなランの位置を手がかりに、この漢字ランの読みを切り出す。
      const next = runs[i + 1];
      let furi: string;
      if (next) {
        const nextHira = kataToHira(next.text);
        const idx = reading.indexOf(nextHira, ri);
        if (idx >= 0) {
          furi = reading.slice(ri, idx);
          ri = idx;
        } else {
          furi = reading.slice(ri);
          ri = reading.length;
        }
      } else {
        furi = reading.slice(ri);
        ri = reading.length;
      }
      segs.push({ text: run.text, rt: furi || undefined });
    }
  }
  return segs;
}

// 単語IDの連番カウンタ（React の key 用。シードに依存せず常に一意）。
let idCounter = 0;

function buildWord(entry: WordEntry, type: WordType, prefix: string): Word {
  return {
    id: `${prefix}${idCounter++}`,
    display: entry.display,
    reading: entry.reading,
    type,
    tokens: tokenizeWord(entry.reading),
  };
}

// 与えられた決定論的 RNG から新しい単語を生成する。
// theme を指定すると、そのテーマ（タグ）の語彙からのみ出題する。
// recent に直近出題した表示テキストを渡すと、それらを避けて選ぶ（連続/近接重複の防止）。
// localType=true のとき、種別（お宝/おじゃま）だけはクライアントごとにローカル乱数で決める。
//   → 出題する単語列（エントリ）はシード共有で全員同じだが、お宝の出現は各自に保証される
//     （オンラインでお宝＝アイテムが特定プレイヤーにしか出ない問題への対策）。
export const generateWord = (
  rng: RNG,
  theme: string = 'all',
  recent: string[] = [],
  localType = false,
  treasureProb = 0.2,
  treasureBonus = 0, // 「お宝出現率アップ」アイテムなどの恒久ボーナス（加算）
): Word => {
  const pool = THEME_POOLS[theme] ?? WORD_POOL;
  let entry = pool[Math.floor(rng() * pool.length)];
  // 直近に出た単語と被ったら引き直す（プールが十分大きいときのみ）。
  // プールサイズに応じて試行回数を増やし、近接重複をしっかり避ける。
  if (recent.length > 0 && pool.length > recent.length + 1) {
    const tries = Math.min(40, pool.length);
    for (let i = 0; i < tries && recent.includes(entry.display); i++) {
      entry = pool[Math.floor(rng() * pool.length)];
    }
  }
  // 種別用の乱数は常にシード列を1つ消費する（エントリ列の同期を崩さない）。
  const seededRand = rng();
  const rand = localType ? Math.random() : seededRand;
  let type: WordType = 'normal';
  if (localType) {
    // オンライン: お宝の出現率はホストが 0〜100% で設定可能（treasureProb）。
    // 相手から飛んでくるおじゃまで割合が薄まるため、自動供給のおじゃまは少なめ（約8%）。
    const tp = Math.min(0.95, Math.max(0, treasureProb + treasureBonus));
    if (rand < tp) type = 'treasure';
    else if (rand < tp + 0.08) type = 'ojama';
  } else {
    // ソロ: お宝出現率はカスタム設定（treasureProb／＋ボーナス）/ おじゃま 約20%。
    const tp = Math.min(0.95, Math.max(0, treasureProb + treasureBonus));
    if (rand < tp) type = 'treasure';
    else if (rand < tp + 0.2) type = 'ojama';
  }
  return buildWord(entry, type, 'w');
};

// 受信したおじゃま用の単語（常に ojama）。攻撃由来なので Math.random で選ぶ。
export const makeOjamaWord = (): Word => {
  const entry = WORD_POOL[Math.floor(Math.random() * WORD_POOL.length)];
  return buildWord(entry, 'ojama', 'o');
};

// 3〜4文字の短い単語プール（アイテム「短縮」用）。
const SHORT_POOL: WordEntry[] = WORD_POOL.filter((w) => w.reading.length >= 3 && w.reading.length <= 4);

// 短い単語を生成（アイテム「短縮」でバックログを軽くするのに使う）。
export const makeShortWord = (type: WordType = 'normal'): Word => {
  const entry = SHORT_POOL[Math.floor(Math.random() * SHORT_POOL.length)];
  return buildWord(entry, type, 's');
};

// アイテム「ロング送信」で相手に送りつける長文（読みは14文字以上）。
// 1個でも打ち切るのに時間がかかる“重い”お邪魔として機能する。
// ロング送信（長文アイテム）専用の長文。読みは14文字以上の普通の文章。
// ことわざは「言い切り形」にして長文ではなくなったため、長文ジャンルからは外し、
// 専用の長文をここで生成して送る。
export const LONG_SENTENCES: WordEntry[] = [
  { display: '今日はとても良い天気で散歩日和だ', reading: 'きょうはとてもよいてんきでさんぽびよりだ' },
  { display: '図書館で借りた本を期限までに返す', reading: 'としょかんでかりたほんをきげんまでにかえす' },
  { display: '明日の会議の資料を今夜中に作る', reading: 'あしたのかいぎのしりょうをこんやじゅうにつくる' },
  { display: '週末は家族と一緒に映画を見に行く', reading: 'しゅうまつはかぞくといっしょにえいがをみにいく' },
  { display: '健康のために毎朝早起きして運動する', reading: 'けんこうのためにまいあさはやおきしてうんどうする' },
  { display: '電車が遅れたので約束に間に合わない', reading: 'でんしゃがおくれたのでやくそくにまにあわない' },
  { display: '夏休みの宿題を計画的に進めていく', reading: 'なつやすみのしゅくだいをけいかくてきにすすめていく' },
  { display: '雨が降りそうなので傘を持って出かける', reading: 'あめがふりそうなのでかさをもってでかける' },
  { display: '期末試験に向けて毎日少しずつ勉強する', reading: 'きまつしけんにむけてまいにちすこしずつべんきょうする' },
  { display: '友達と待ち合わせて買い物に出かけた', reading: 'ともだちとまちあわせてかいものにでかけた' },
  { display: '締め切りが近いので集中して仕上げる', reading: 'しめきりがちかいのでしゅうちゅうしてしあげる' },
  { display: '朝ごはんをしっかり食べて学校へ行く', reading: 'あさごはんをしっかりたべてがっこうへいく' },
  { display: '部屋を片付けてから友達を家に呼ぶ', reading: 'へやをかたづけてからともだちをいえによぶ' },
  { display: '新しい言葉を覚えるのは時間がかかる', reading: 'あたらしいことばをおぼえるのはじかんがかかる' },
  { display: '夕食の後に家族みんなで散歩をする', reading: 'ゆうしょくのあとにかぞくみんなでさんぽをする' },
  { display: '仕事の合間に温かいお茶で一息つく', reading: 'しごとのあいまにあたたかいおちゃでひといきつく' },
  { display: '週末の天気が良ければ山に登りたい', reading: 'しゅうまつのてんきがよければやまにのぼりたい' },
  { display: '自転車で通学する途中に猫を見かけた', reading: 'じてんしゃでつうがくするとちゅうにねこをみかけた' },
  { display: '引っ越しの準備で荷物をまとめている', reading: 'ひっこしのじゅんびでにもつをまとめている' },
  { display: '試合に勝つために毎日練習を続ける', reading: 'しあいにかつためにまいにちれんしゅうをつづける' },
  { display: '雪が積もったので朝早く雪かきをした', reading: 'ゆきがつもったのであさはやくゆきかきをした' },
  { display: '誕生日に欲しかった本を買ってもらう', reading: 'たんじょうびにほしかったほんをかってもらう' },
  { display: '庭に咲いた花に毎朝水をあげている', reading: 'にわにさいたはなにまいあさみずをあげている' },
  { display: '窓を開けて朝の涼しい風を入れる', reading: 'まどをあけてあさのすずしいかぜをいれる' },
  { display: '駅まで歩いて電車に乗り換える', reading: 'えきまであるいてでんしゃにのりかえる' },
  { display: '本屋で面白そうな小説を見つけた', reading: 'ほんやでおもしろそうなしょうせつをみつけた' },
  { display: '台所で夕飯の支度を急いでする', reading: 'だいどころでゆうはんのしたくをいそいでする' },
  { display: '紅茶に砂糖を入れてゆっくり飲む', reading: 'こうちゃにさとうをいれてゆっくりのむ' },
  { display: '朝市で新鮮な野菜をたくさん買った', reading: 'あさいちでしんせんなやさいをたくさんかった' },
  { display: '公園を散歩しながら音楽を聴いた', reading: 'こうえんをさんぽしながらおんがくをきいた' },
  { display: '休日は早起きしてパンを焼くのが楽しみだ', reading: 'きゅうじつははやおきしてぱんをやくのがたのしみだ' },
  { display: '彼は約束の時間にいつも遅れてくる', reading: 'かれはやくそくのじかんにいつもおくれてくる' },
  { display: '図書館は静かで集中できる良い場所だ', reading: 'としょかんはしずかでしゅうちゅうできるよいばしょだ' },
  { display: '初めての街で道に迷ってしまった', reading: 'はじめてのまちでみちにまよってしまった' },
  { display: '夜空にきれいな星がたくさん輝いている', reading: 'よぞらにきれいなほしがたくさんかがやいている' },
  { display: '料理が得意な友人に作り方を教わる', reading: 'りょうりがとくいなゆうじんにつくりかたをおそわる' },
  { display: '長い坂道を自転車で一気に駆け下りた', reading: 'ながいさかみちをじてんしゃでいっきにかけおりた' },
  { display: '春になると庭の桜が一斉に咲き始める', reading: 'はるになるとにわのさくらがいっせいにさきはじめる' },
  { display: '大切な書類を机の引き出しにしまった', reading: 'たいせつなしょるいをつくえのひきだしにしまった' },
  { display: '海辺で拾った貝殻を箱に集めている', reading: 'うみべでひろったかいがらをはこにあつめている' },
  { display: '雨上がりの空に大きな虹がかかった', reading: 'あめあがりのそらにおおきなにじがかかった' },
  { display: '弟と協力して庭に小屋を作っている', reading: 'おとうとときょうりょくしてにわにこやをつくっている' },
  { display: '美味しい匂いに誘われて店に入った', reading: 'おいしいにおいにさそわれてみせにはいった' },
  { display: '宿題を終わらせてからゲームで遊ぶ', reading: 'しゅくだいをおわらせてからげーむであそぶ' },
  { display: '遠くの山々が朝日に赤く染まっている', reading: 'とおくのやまやまがあさひにあかくそまっている' },
  { display: '毎週日曜は祖母の家に遊びに行く', reading: 'まいしゅうにちようはそぼのいえにあそびにいく' },
  { display: '冷たい川の水に足をつけて涼んだ', reading: 'つめたいかわのみずにあしをつけてすずんだ' },
  { display: '電車の窓から流れる景色を眺めていた', reading: 'でんしゃのまどからながれるけしきをながめていた' },
  { display: '熱心に練習した曲をみんなの前で弾く', reading: 'ねっしんにれんしゅうしたきょくをみんなのまえでひく' },
];

// ロング送信用の長文をランダムに選ぶ（表示と読みのペア）。
export const randomLongWord = (): { display: string; reading: string } => {
  const e = LONG_SENTENCES[Math.floor(Math.random() * LONG_SENTENCES.length)];
  return { display: e.display, reading: e.reading };
};

// 指定の表示・読みからおじゃま単語を生成（受信したロング送信の挿入用）。
export const makeOjamaWordFrom = (display: string, reading: string): Word => ({
  id: `o${idCounter++}`,
  display,
  reading,
  type: 'ojama',
  tokens: tokenizeWord(reading),
});

// --- 出題テーマ（タグ） ---
// 語彙をタグで分類し、テーマを選んで出題範囲を絞れるようにする。
export interface Theme {
  id: string;
  label: string;
}

// 通常出題は「単語のみ」。長文はロング送信アイテム専用にするためテーマには
// 含めない（LONG_SENTENCES は makeOjamaWordFrom 経由でのみ出現）。
export const THEMES: Theme[] = [
  { id: 'all', label: 'すべて' },
  { id: 'greeting', label: 'あいさつ' },
  { id: 'it', label: 'IT・ゲーム' },
  { id: 'food', label: '食べ物' },
  { id: 'nature', label: '自然・乗物' },
  { id: 'school', label: '学校・生活' },
];

// テーマごとの語彙プール。'all' は全語彙（WORD_POOL）を使う。
const THEME_POOLS: Record<string, WordEntry[]> = {
  greeting: [
    { display: 'ありがとう', reading: 'ありがとう' },
    { display: 'こんにちは', reading: 'こんにちは' },
    { display: '宜しく', reading: 'よろしく' },
    { display: '頑張って', reading: 'がんばって' },
    { display: 'お疲れ様', reading: 'おつかれさま' },
    { display: '初めまして', reading: 'はじめまして' },
    { display: 'おはよう', reading: 'おはよう' },
    { display: 'こんばんは', reading: 'こんばんは' },
    { display: 'さようなら', reading: 'さようなら' },
    { display: 'おやすみ', reading: 'おやすみ' },
    { display: 'ただいま', reading: 'ただいま' },
    { display: 'おかえり', reading: 'おかえり' },
    { display: '頂きます', reading: 'いただきます' },
    { display: 'ご馳走様', reading: 'ごちそうさま' },
    { display: 'すみません', reading: 'すみません' },
    { display: 'ごめんなさい', reading: 'ごめんなさい' },
    { display: 'お願いします', reading: 'おねがいします' },
    { display: '失礼します', reading: 'しつれいします' },
    { display: 'お元気ですか', reading: 'おげんきですか' },
    { display: '久しぶり', reading: 'ひさしぶり' },
    { display: 'おめでとう', reading: 'おめでとう' },
    { display: '行ってきます', reading: 'いってきます' },
    { display: '行ってらっしゃい', reading: 'いってらっしゃい' },
    { display: '大丈夫', reading: 'だいじょうぶ' },
    { display: '気を付けて', reading: 'きをつけて' },
    { display: 'また明日', reading: 'またあした' },
    { display: 'お先に', reading: 'おさきに' },
    { display: '助かります', reading: 'たすかります' },
    { display: '感謝', reading: 'かんしゃ' },
    { display: '乾杯', reading: 'かんぱい' },
    { display: 'いらっしゃい', reading: 'いらっしゃい' },
    { display: 'かしこまりました', reading: 'かしこまりました' },
    { display: '承知しました', reading: 'しょうちしました' },
    { display: '楽しかった', reading: 'たのしかった' },
    { display: '嬉しい', reading: 'うれしい' },
    { display: '頑張ろう', reading: 'がんばろう' },
    { display: '応援', reading: 'おうえん' },
    { display: 'お大事に', reading: 'おだいじに' },
    { display: 'ようこそ', reading: 'ようこそ' },
    { display: '始めよう', reading: 'はじめよう' },
    { display: 'ご機嫌よう', reading: 'ごきげんよう' },
    { display: 'おやすみなさい', reading: 'おやすみなさい' },
    { display: 'どうぞ', reading: 'どうぞ' },
    { display: '素敵だね', reading: 'すてきだね' },
    { display: 'なるほど', reading: 'なるほど' },
    { display: 'もちろん', reading: 'もちろん' },
    { display: '元気だよ', reading: 'げんきだよ' },
    { display: 'こちらこそ', reading: 'こちらこそ' },
    { display: 'お邪魔します', reading: 'おじゃまします' },
    { display: 'また会おう', reading: 'またあおう' },
    { display: 'はじめまして', reading: 'はじめまして' },
    { display: 'よろしくね', reading: 'よろしくね' },
    { display: 'お久しぶり', reading: 'おひさしぶり' },
    { display: 'お世話になります', reading: 'おせわになります' },
    { display: 'ご無沙汰', reading: 'ごぶさた' },
    { display: 'おはようございます', reading: 'おはようございます' },
    { display: 'こんばんわ', reading: 'こんばんわ' },
    { display: 'いってきます', reading: 'いってきます' },
    { display: 'ただいま帰りました', reading: 'ただいまかえりました' },
    { display: 'おかえりなさい', reading: 'おかえりなさい' },
    { display: 'お休みなさい', reading: 'おやすみなさい' },
    { display: 'いただきます', reading: 'いただきます' },
    { display: 'ごちそうさまでした', reading: 'ごちそうさまでした' },
    { display: '失礼しました', reading: 'しつれいしました' },
    { display: '恐れ入ります', reading: 'おそれいります' },
    { display: 'お疲れさまでした', reading: 'おつかれさまでした' },
    { display: 'お先に失礼します', reading: 'おさきにしつれいします' },
    { display: 'ありがとうございます', reading: 'ありがとうございます' },
    { display: 'どういたしまして', reading: 'どういたしまして' },
    { display: '申し訳ない', reading: 'もうしわけない' },
    { display: 'お詫び', reading: 'おわび' },
    { display: '了解です', reading: 'りょうかいです' },
    { display: '承知いたしました', reading: 'しょうちいたしました' },
    { display: 'かしこまりました', reading: 'かしこまりました' },
    { display: 'お任せください', reading: 'おまかせください' },
    { display: 'お気をつけて', reading: 'おきをつけて' },
    { display: 'ご安全に', reading: 'ごあんぜんに' },
    { display: 'お大事になさってください', reading: 'おだいじになさってください' },
    { display: 'おめでとうございます', reading: 'おめでとうございます' },
    { display: 'お祝い', reading: 'おいわい' },
    { display: '心から感謝', reading: 'こころからかんしゃ' },
    { display: 'ご協力', reading: 'ごきょうりょく' },
    { display: 'よろしくお願いいたします', reading: 'よろしくおねがいいたします' },
    { display: '初対面', reading: 'しょたいめん' },
    { display: '自己紹介', reading: 'じこしょうかい' },
    { display: '握手', reading: 'あくしゅ' },
    { display: '会釈', reading: 'えしゃく' },
    { display: 'お辞儀', reading: 'おじぎ' },
    { display: '挨拶回り', reading: 'あいさつまわり' },
    { display: 'お言葉に甘えて', reading: 'おことばにあまえて' },
    { display: '気にしないで', reading: 'きにしないで' },
    { display: '遠慮なく', reading: 'えんりょなく' },
    { display: 'お構いなく', reading: 'おかまいなく' },
    { display: 'ご機嫌いかが', reading: 'ごきげんいかが' },
    { display: '調子はどう', reading: 'ちょうしはどう' },
    { display: 'またね', reading: 'またね' },
    { display: 'バイバイ', reading: 'ばいばい' },
    { display: 'いってらっしゃい', reading: 'いってらっしゃい' },
    { display: 'お帰りなさいませ', reading: 'おかえりなさいませ' },
    { display: '楽しんでね', reading: 'たのしんでね' },
    { display: '無理しないで', reading: 'むりしないで' },
    { display: 'がんばってね', reading: 'がんばってね' },
    { display: '応援してるよ', reading: 'おうえんしてるよ' },
    { display: 'おつかれ', reading: 'おつかれ' },
    { display: 'よくやった', reading: 'よくやった' },
    { display: '素晴らしい', reading: 'すばらしい' },
    { display: 'お見事', reading: 'おみごと' },
    { display: 'おかげさまで', reading: 'おかげさまで' },
    { display: 'お言葉ですが', reading: 'おことばですが' },
    { display: 'ご一緒に', reading: 'ごいっしょに' },
    { display: 'またお会いしましょう', reading: 'またおあいしましょう' },
    { display: 'ご縁', reading: 'ごえん' },
    { display: '感謝感激', reading: 'かんしゃかんげき' },
    { display: 'おもてなし', reading: 'おもてなし' },
    { display: 'お招き', reading: 'おまねき' },
    { display: 'ご訪問', reading: 'ごほうもん' },
    { display: 'ご来店', reading: 'ごらいてん' },
    { display: 'ようこそお越し', reading: 'ようこそおこし' },
  ],
  it: [
    { display: 'タイピング', reading: 'たいぴんぐ' },
    { display: 'キーボード', reading: 'きーぼーど' },
    { display: 'マウス', reading: 'まうす' },
    { display: 'パソコン', reading: 'ぱそこん' },
    { display: 'インターネット', reading: 'いんたーねっと' },
    { display: 'プログラミング', reading: 'ぷろぐらみんぐ' },
    { display: '技術者', reading: 'ぎじゅつしゃ' },
    { display: '開発', reading: 'かいはつ' },
    { display: '画面', reading: 'がめん' },
    { display: '通信', reading: 'つうしん' },
    { display: '対戦', reading: 'たいせん' },
    { display: '連鎖', reading: 'れんさ' },
    { display: '攻撃', reading: 'こうげき' },
    { display: '逆転', reading: 'ぎゃくてん' },
    { display: '勝利', reading: 'しょうり' },
    { display: 'ソフト', reading: 'そふと' },
    { display: 'ハード', reading: 'はーど' },
    { display: 'アプリ', reading: 'あぷり' },
    { display: 'データ', reading: 'でーた' },
    { display: 'ファイル', reading: 'ふぁいる' },
    { display: 'フォルダ', reading: 'ふぉるだ' },
    { display: 'サーバー', reading: 'さーばー' },
    { display: 'ネットワーク', reading: 'ねっとわーく' },
    { display: 'ログイン', reading: 'ろぐいん' },
    { display: 'パスワード', reading: 'ぱすわーど' },
    { display: 'ダウンロード', reading: 'だうんろーど' },
    { display: 'アップロード', reading: 'あっぷろーど' },
    { display: 'インストール', reading: 'いんすとーる' },
    { display: 'アップデート', reading: 'あっぷでーと' },
    { display: 'クリック', reading: 'くりっく' },
    { display: 'スクロール', reading: 'すくろーる' },
    { display: 'ブラウザ', reading: 'ぶらうざ' },
    { display: '検索', reading: 'けんさく' },
    { display: '画像', reading: 'がぞう' },
    { display: '動画', reading: 'どうが' },
    { display: '設定', reading: 'せってい' },
    { display: '保存', reading: 'ほぞん' },
    { display: '編集', reading: 'へんしゅう' },
    { display: '削除', reading: 'さくじょ' },
    { display: '入力', reading: 'にゅうりょく' },
    { display: '出力', reading: 'しゅつりょく' },
    { display: '変数', reading: 'へんすう' },
    { display: '関数', reading: 'かんすう' },
    { display: '配列', reading: 'はいれつ' },
    { display: '条件分岐', reading: 'じょうけんぶんき' },
    { display: '繰り返し', reading: 'くりかえし' },
    { display: '実行', reading: 'じっこう' },
    { display: '暗号化', reading: 'あんごうか' },
    { display: '再起動', reading: 'さいきどう' },
    { display: '接続', reading: 'せつぞく' },
    { display: '必殺技', reading: 'ひっさつわざ' },
    { display: '連勝', reading: 'れんしょう' },
    { display: 'スマートフォン', reading: 'すまーとふぉん' },
    { display: 'タブレット', reading: 'たぶれっと' },
    { display: 'ノートパソコン', reading: 'のーとぱそこん' },
    { display: 'モニター', reading: 'もにたー' },
    { display: 'スピーカー', reading: 'すぴーかー' },
    { display: 'イヤホン', reading: 'いやほん' },
    { display: 'マイク', reading: 'まいく' },
    { display: 'カメラ', reading: 'かめら' },
    { display: 'プリンター', reading: 'ぷりんたー' },
    { display: 'ルーター', reading: 'るーたー' },
    { display: '充電器', reading: 'じゅうでんき' },
    { display: '電池', reading: 'でんち' },
    { display: '画素', reading: 'がそ' },
    { display: '解像度', reading: 'かいぞうど' },
    { display: '通信速度', reading: 'つうしんそくど' },
    { display: '回線', reading: 'かいせん' },
    { display: '無線', reading: 'むせん' },
    { display: '有線', reading: 'ゆうせん' },
    { display: '同期', reading: 'どうき' },
    { display: '更新', reading: 'こうしん' },
    { display: '互換性', reading: 'ごかんせい' },
    { display: '拡張子', reading: 'かくちょうし' },
    { display: '圧縮', reading: 'あっしゅく' },
    { display: '解凍', reading: 'かいとう' },
    { display: '署名', reading: 'しょめい' },
    { display: '認証', reading: 'にんしょう' },
    { display: '権限', reading: 'けんげん' },
    { display: '管理者', reading: 'かんりしゃ' },
    { display: '利用者', reading: 'りようしゃ' },
    { display: '会員登録', reading: 'かいいんとうろく' },
    { display: '退会', reading: 'たいかい' },
    { display: '課金', reading: 'かきん' },
    { display: '無料体験', reading: 'むりょうたいけん' },
    { display: '定期購読', reading: 'ていきこうどく' },
    { display: '配信', reading: 'はいしん' },
    { display: '生放送', reading: 'なまほうそう' },
    { display: '視聴者', reading: 'しちょうしゃ' },
    { display: '実況', reading: 'じっきょう' },
    { display: '攻略', reading: 'こうりゃく' },
    { display: '裏技', reading: 'うらわざ' },
    { display: '隠し要素', reading: 'かくしようそ' },
    { display: '経験値', reading: 'けいけんち' },
    { display: '回復', reading: 'かいふく' },
    { display: '装備', reading: 'そうび' },
    { display: '武器', reading: 'ぶき' },
    { display: '防具', reading: 'ぼうぐ' },
    { display: '盾', reading: 'たて' },
    { display: '魔法', reading: 'まほう' },
    { display: '呪文', reading: 'じゅもん' },
    { display: '召喚', reading: 'しょうかん' },
    { display: '効果音', reading: 'こうかおん' },
    { display: '背景', reading: 'はいけい' },
    { display: '操作', reading: 'そうさ' },
    { display: '難易度', reading: 'なんいど' },
    { display: '達成率', reading: 'たっせいりつ' },
    { display: '初期化', reading: 'しょきか' },
    { display: '読み込み', reading: 'よみこみ' },
    { display: '書き込み', reading: 'かきこみ' },
    { display: '上書き保存', reading: 'うわがきほぞん' },
    { display: '自動保存', reading: 'じどうほぞん' },
    { display: '復元', reading: 'ふくげん' },
    { display: '同時接続', reading: 'どうじせつぞく' },
    { display: '待機画面', reading: 'たいきがめん' },
    { display: '通知', reading: 'つうち' },
    { display: '迷惑メール', reading: 'めいわくめーる' },
    { display: '添付', reading: 'てんぷ' },
    { display: '返信', reading: 'へんしん' },
    { display: '転送', reading: 'てんそう' },
    { display: '下書き', reading: 'したがき' },
    { display: '送信', reading: 'そうしん' },
  ],
  food: [
    { display: 'お握り', reading: 'おにぎり' },
    { display: 'ハンバーガー', reading: 'はんばーがー' },
    { display: '拉麺', reading: 'らーめん' },
    { display: '林檎', reading: 'りんご' },
    { display: '蜜柑', reading: 'みかん' },
    { display: '西瓜', reading: 'すいか' },
    { display: '寿司', reading: 'すし' },
    { display: '味噌汁', reading: 'みそしる' },
    { display: '玉子焼き', reading: 'たまごやき' },
    { display: '珈琲', reading: 'こーひー' },
    { display: 'カレー', reading: 'かれー' },
    { display: 'うどん', reading: 'うどん' },
    { display: '蕎麦', reading: 'そば' },
    { display: '焼き鳥', reading: 'やきとり' },
    { display: '唐揚げ', reading: 'からあげ' },
    { display: '餃子', reading: 'ぎょうざ' },
    { display: '天ぷら', reading: 'てんぷら' },
    { display: '刺身', reading: 'さしみ' },
    { display: '牛丼', reading: 'ぎゅうどん' },
    { display: '親子丼', reading: 'おやこどん' },
    { display: 'お好み焼き', reading: 'おこのみやき' },
    { display: 'たこ焼き', reading: 'たこやき' },
    { display: '焼きそば', reading: 'やきそば' },
    { display: '団子', reading: 'だんご' },
    { display: '大福', reading: 'だいふく' },
    { display: '羊羹', reading: 'ようかん' },
    { display: '煎餅', reading: 'せんべい' },
    { display: '苺', reading: 'いちご' },
    { display: '葡萄', reading: 'ぶどう' },
    { display: '桃', reading: 'もも' },
    { display: '梨', reading: 'なし' },
    { display: '柿', reading: 'かき' },
    { display: 'バナナ', reading: 'ばなな' },
    { display: 'メロン', reading: 'めろん' },
    { display: '人参', reading: 'にんじん' },
    { display: '玉葱', reading: 'たまねぎ' },
    { display: '馬鈴薯', reading: 'じゃがいも' },
    { display: '南瓜', reading: 'かぼちゃ' },
    { display: '茄子', reading: 'なす' },
    { display: '胡瓜', reading: 'きゅうり' },
    { display: '卵', reading: 'たまご' },
    { display: '牛乳', reading: 'ぎゅうにゅう' },
    { display: '紅茶', reading: 'こうちゃ' },
    { display: '緑茶', reading: 'りょくちゃ' },
    { display: '炭酸水', reading: 'たんさんすい' },
    { display: '砂糖', reading: 'さとう' },
    { display: '胡椒', reading: 'こしょう' },
    { display: '弁当', reading: 'べんとう' },
    { display: '朝食', reading: 'ちょうしょく' },
    { display: '夕食', reading: 'ゆうしょく' },
    { display: '食欲', reading: 'しょくよく' },
    { display: 'チャーハン', reading: 'ちゃーはん' },
    { display: '春巻き', reading: 'はるまき' },
    { display: '麻婆豆腐', reading: 'まーぼーどうふ' },
    { display: '酢豚', reading: 'すぶた' },
    { display: '冷やし中華', reading: 'ひやしちゅうか' },
    { display: 'つけ麺', reading: 'つけめん' },
    { display: 'ざるそば', reading: 'ざるそば' },
    { display: 'きつねうどん', reading: 'きつねうどん' },
    { display: 'おでん', reading: 'おでん' },
    { display: '茶碗蒸し', reading: 'ちゃわんむし' },
    { display: '肉じゃが', reading: 'にくじゃが' },
    { display: '味噌煮込み', reading: 'みそにこみ' },
    { display: '豚汁', reading: 'とんじる' },
    { display: 'おにぎらず', reading: 'おにぎらず' },
    { display: '稲荷寿司', reading: 'いなりずし' },
    { display: '海苔巻き', reading: 'のりまき' },
    { display: 'ちらし寿司', reading: 'ちらしずし' },
    { display: '握り寿司', reading: 'にぎりずし' },
    { display: '回転寿司', reading: 'かいてんずし' },
    { display: 'コロッケ', reading: 'ころっけ' },
    { display: 'メンチカツ', reading: 'めんちかつ' },
    { display: 'とんかつ', reading: 'とんかつ' },
    { display: 'エビフライ', reading: 'えびふらい' },
    { display: 'ハンバーグ', reading: 'はんばーぐ' },
    { display: 'オムライス', reading: 'おむらいす' },
    { display: 'ナポリタン', reading: 'なぽりたん' },
    { display: 'グラタン', reading: 'ぐらたん' },
    { display: 'ドリア', reading: 'どりあ' },
    { display: 'ピザ', reading: 'ぴざ' },
    { display: 'サンドイッチ', reading: 'さんどいっち' },
    { display: 'ホットドッグ', reading: 'ほっとどっぐ' },
    { display: 'ポテト', reading: 'ぽてと' },
    { display: 'サラダ', reading: 'さらだ' },
    { display: 'スープ', reading: 'すーぷ' },
    { display: 'シチュー', reading: 'しちゅー' },
    { display: 'ポトフ', reading: 'ぽとふ' },
    { display: 'パンケーキ', reading: 'ぱんけーき' },
    { display: 'ホットケーキ', reading: 'ほっとけーき' },
    { display: 'クレープ', reading: 'くれーぷ' },
    { display: 'ドーナツ', reading: 'どーなつ' },
    { display: 'プリン', reading: 'ぷりん' },
    { display: 'ゼリー', reading: 'ぜりー' },
    { display: 'アイスクリーム', reading: 'あいすくりーむ' },
    { display: 'かき氷', reading: 'かきごおり' },
    { display: 'チョコレート', reading: 'ちょこれーと' },
    { display: 'クッキー', reading: 'くっきー' },
    { display: 'ビスケット', reading: 'びすけっと' },
    { display: 'マカロン', reading: 'まかろん' },
    { display: 'わたあめ', reading: 'わたあめ' },
    { display: 'みたらし団子', reading: 'みたらしだんご' },
    { display: '柏餅', reading: 'かしわもち' },
    { display: '草餅', reading: 'くさもち' },
    { display: 'たい焼き', reading: 'たいやき' },
    { display: '今川焼き', reading: 'いまがわやき' },
    { display: 'みかんゼリー', reading: 'みかんぜりー' },
    { display: 'パイナップル', reading: 'ぱいなっぷる' },
    { display: 'キウイ', reading: 'きうい' },
    { display: 'さくらんぼ', reading: 'さくらんぼ' },
    { display: 'びわ', reading: 'びわ' },
    { display: 'いちじく', reading: 'いちじく' },
    { display: 'ざくろ', reading: 'ざくろ' },
    { display: 'キャベツ', reading: 'きゃべつ' },
    { display: 'レタス', reading: 'れたす' },
    { display: 'ほうれん草', reading: 'ほうれんそう' },
    { display: '小松菜', reading: 'こまつな' },
    { display: 'ブロッコリー', reading: 'ぶろっこりー' },
    { display: 'とうもろこし', reading: 'とうもろこし' },
    { display: '枝豆', reading: 'えだまめ' },
    { display: '大根', reading: 'だいこん' },
    { display: 'ごぼう', reading: 'ごぼう' },
    { display: 'れんこん', reading: 'れんこん' },
    { display: 'しいたけ', reading: 'しいたけ' },
  ],
  nature: [
    { display: '太陽', reading: 'たいよう' },
    { display: '宇宙', reading: 'うちゅう' },
    { display: '青空', reading: 'あおぞら' },
    { display: '新幹線', reading: 'しんかんせん' },
    { display: '飛行機', reading: 'ひこうき' },
    { display: '自転車', reading: 'じてんしゃ' },
    { display: '電車', reading: 'でんしゃ' },
    { display: '海', reading: 'うみ' },
    { display: '山', reading: 'やま' },
    { display: '川', reading: 'かわ' },
    { display: '森林', reading: 'しんりん' },
    { display: '稲妻', reading: 'いなずま' },
    { display: '月', reading: 'つき' },
    { display: '星', reading: 'ほし' },
    { display: '雲', reading: 'くも' },
    { display: '雨', reading: 'あめ' },
    { display: '雪', reading: 'ゆき' },
    { display: '風', reading: 'かぜ' },
    { display: '雷', reading: 'かみなり' },
    { display: '虹', reading: 'にじ' },
    { display: '台風', reading: 'たいふう' },
    { display: '地震', reading: 'じしん' },
    { display: '火山', reading: 'かざん' },
    { display: '砂漠', reading: 'さばく' },
    { display: '湖', reading: 'みずうみ' },
    { display: '滝', reading: 'たき' },
    { display: '島', reading: 'しま' },
    { display: '銀河', reading: 'ぎんが' },
    { display: '惑星', reading: 'わくせい' },
    { display: '彗星', reading: 'すいせい' },
    { display: '衛星', reading: 'えいせい' },
    { display: '草原', reading: 'そうげん' },
    { display: '紅葉', reading: 'こうよう' },
    { display: '桜', reading: 'さくら' },
    { display: '自動車', reading: 'じどうしゃ' },
    { display: 'バス', reading: 'ばす' },
    { display: 'タクシー', reading: 'たくしー' },
    { display: '地下鉄', reading: 'ちかてつ' },
    { display: '船', reading: 'ふね' },
    { display: '客船', reading: 'きゃくせん' },
    { display: 'ロケット', reading: 'ろけっと' },
    { display: '気球', reading: 'ききゅう' },
    { display: '救急車', reading: 'きゅうきゅうしゃ' },
    { display: '消防車', reading: 'しょうぼうしゃ' },
    { display: '路面電車', reading: 'ろめんでんしゃ' },
    { display: '貨物列車', reading: 'かもつれっしゃ' },
    { display: '高速道路', reading: 'こうそくどうろ' },
    { display: '信号機', reading: 'しんごうき' },
    { display: '踏切', reading: 'ふみきり' },
    { display: '渡り鳥', reading: 'わたりどり' },
    { display: '朝焼け', reading: 'あさやけ' },
    { display: '夕焼け', reading: 'ゆうやけ' },
    { display: '朝露', reading: 'あさつゆ' },
    { display: '霧', reading: 'きり' },
    { display: '霜', reading: 'しも' },
    { display: '吹雪', reading: 'ふぶき' },
    { display: '木漏れ日', reading: 'こもれび' },
    { display: '稲穂', reading: 'いなほ' },
    { display: '若葉', reading: 'わかば' },
    { display: '落ち葉', reading: 'おちば' },
    { display: '枯れ葉', reading: 'かれは' },
    { display: '新緑', reading: 'しんりょく' },
    { display: '花畑', reading: 'はなばたけ' },
    { display: '菜の花', reading: 'なのはな' },
    { display: '向日葵', reading: 'ひまわり' },
    { display: '紫陽花', reading: 'あじさい' },
    { display: '蒲公英', reading: 'たんぽぽ' },
    { display: '朝顔', reading: 'あさがお' },
    { display: 'すすき', reading: 'すすき' },
    { display: '松ぼっくり', reading: 'まつぼっくり' },
    { display: '木の実', reading: 'きのみ' },
    { display: '苔', reading: 'こけ' },
    { display: '渓流', reading: 'けいりゅう' },
    { display: '入り江', reading: 'いりえ' },
    { display: '岬', reading: 'みさき' },
    { display: '砂浜', reading: 'すなはま' },
    { display: '波', reading: 'なみ' },
    { display: '潮風', reading: 'しおかぜ' },
    { display: '干潟', reading: 'ひがた' },
    { display: '珊瑚礁', reading: 'さんごしょう' },
    { display: '洞窟', reading: 'どうくつ' },
    { display: '渓谷', reading: 'けいこく' },
    { display: '尾根', reading: 'おね' },
    { display: '山頂', reading: 'さんちょう' },
    { display: '高原', reading: 'こうげん' },
    { display: '湿原', reading: 'しつげん' },
    { display: '雪原', reading: 'せつげん' },
    { display: '大地', reading: 'だいち' },
    { display: '地平線', reading: 'ちへいせん' },
    { display: '水平線', reading: 'すいへいせん' },
    { display: 'オーロラ', reading: 'おーろら' },
    { display: '蜃気楼', reading: 'しんきろう' },
    { display: '夜明け', reading: 'よあけ' },
    { display: '日の出', reading: 'ひので' },
    { display: '日の入り', reading: 'ひのいり' },
    { display: '満天の星', reading: 'まんてんのほし' },
    { display: '天の川', reading: 'あまのがわ' },
    { display: '星座', reading: 'せいざ' },
    { display: 'モノレール', reading: 'ものれーる' },
    { display: 'ケーブルカー', reading: 'けーぶるかー' },
    { display: 'リニアモーターカー', reading: 'りにあもーたーかー' },
    { display: '観光バス', reading: 'かんこうばす' },
    { display: '路線バス', reading: 'ろせんばす' },
    { display: 'トラック', reading: 'とらっく' },
    { display: 'オートバイ', reading: 'おーとばい' },
    { display: 'ヘリコプター', reading: 'へりこぷたー' },
    { display: '飛行船', reading: 'ひこうせん' },
    { display: '潜水艦', reading: 'せんすいかん' },
    { display: 'ヨット', reading: 'よっと' },
    { display: 'いかだ', reading: 'いかだ' },
    { display: 'カヌー', reading: 'かぬー' },
    { display: '人工衛星', reading: 'じんこうえいせい' },
    { display: '宇宙船', reading: 'うちゅうせん' },
    { display: '探査機', reading: 'たんさき' },
    { display: '空港', reading: 'くうこう' },
    { display: '港', reading: 'みなと' },
    { display: '灯台', reading: 'とうだい' },
    { display: '渋滞', reading: 'じゅうたい' },
    { display: '線路', reading: 'せんろ' },
    { display: '駅前', reading: 'えきまえ' },
  ],
  school: [
    { display: '小学校', reading: 'しょうがっこう' },
    { display: '大学', reading: 'だいがく' },
    { display: '図書館', reading: 'としょかん' },
    { display: '宿題', reading: 'しゅくだい' },
    { display: '友達', reading: 'ともだち' },
    { display: '家族', reading: 'かぞく' },
    { display: '音楽', reading: 'おんがく' },
    { display: '映画', reading: 'えいが' },
    { display: '物語', reading: 'ものがたり' },
    { display: '挑戦', reading: 'ちょうせん' },
    { display: '冒険', reading: 'ぼうけん' },
    { display: '出発', reading: 'しゅっぱつ' },
    { display: '集中', reading: 'しゅうちゅう' },
    { display: '中学校', reading: 'ちゅうがっこう' },
    { display: '高校', reading: 'こうこう' },
    { display: '教室', reading: 'きょうしつ' },
    { display: '黒板', reading: 'こくばん' },
    { display: '先生', reading: 'せんせい' },
    { display: '生徒', reading: 'せいと' },
    { display: '授業', reading: 'じゅぎょう' },
    { display: '試験', reading: 'しけん' },
    { display: '成績', reading: 'せいせき' },
    { display: '部活', reading: 'ぶかつ' },
    { display: '文化祭', reading: 'ぶんかさい' },
    { display: '運動会', reading: 'うんどうかい' },
    { display: '修学旅行', reading: 'しゅうがくりょこう' },
    { display: '給食', reading: 'きゅうしょく' },
    { display: '通学路', reading: 'つうがくろ' },
    { display: '教科書', reading: 'きょうかしょ' },
    { display: '鉛筆', reading: 'えんぴつ' },
    { display: '消しゴム', reading: 'けしごむ' },
    { display: '定規', reading: 'じょうぎ' },
    { display: '体育館', reading: 'たいいくかん' },
    { display: '委員長', reading: 'いいんちょう' },
    { display: '遅刻', reading: 'ちこく' },
    { display: '出席', reading: 'しゅっせき' },
    { display: '卒業式', reading: 'そつぎょうしき' },
    { display: '入学式', reading: 'にゅうがくしき' },
    { display: '制服', reading: 'せいふく' },
    { display: '部屋', reading: 'へや' },
    { display: '台所', reading: 'だいどころ' },
    { display: '玄関', reading: 'げんかん' },
    { display: '洗濯', reading: 'せんたく' },
    { display: '掃除', reading: 'そうじ' },
    { display: '料理', reading: 'りょうり' },
    { display: '買い物', reading: 'かいもの' },
    { display: '散歩', reading: 'さんぽ' },
    { display: '仕事', reading: 'しごと' },
    { display: '休日', reading: 'きゅうじつ' },
    { display: '趣味', reading: 'しゅみ' },
    { display: '健康', reading: 'けんこう' },
    { display: '約束', reading: 'やくそく' },
    { display: '節約', reading: 'せつやく' },
    { display: '時間割', reading: 'じかんわり' },
    { display: '黒板消し', reading: 'こくばんけし' },
    { display: 'チョーク', reading: 'ちょーく' },
    { display: '出席番号', reading: 'しゅっせきばんごう' },
    { display: '学級委員', reading: 'がっきゅういいん' },
    { display: '日直', reading: 'にっちょく' },
    { display: '掃除当番', reading: 'そうじとうばん' },
    { display: '給食当番', reading: 'きゅうしょくとうばん' },
    { display: '理科室', reading: 'りかしつ' },
    { display: '音楽室', reading: 'おんがくしつ' },
    { display: '美術室', reading: 'びじゅつしつ' },
    { display: '家庭科室', reading: 'かていかしつ' },
    { display: '職員室', reading: 'しょくいんしつ' },
    { display: '校長室', reading: 'こうちょうしつ' },
    { display: '校庭', reading: 'こうてい' },
    { display: '昇降口', reading: 'しょうこうぐち' },
    { display: '上履き', reading: 'うわばき' },
    { display: '下駄箱', reading: 'げたばこ' },
    { display: '運動着', reading: 'うんどうぎ' },
    { display: '体操服', reading: 'たいそうふく' },
    { display: '通知表', reading: 'つうちひょう' },
    { display: '連絡帳', reading: 'れんらくちょう' },
    { display: '時間目', reading: 'じかんめ' },
    { display: '休み時間', reading: 'やすみじかん' },
    { display: '昼休み', reading: 'ひるやすみ' },
    { display: '放課後', reading: 'ほうかご' },
    { display: '部活動', reading: 'ぶかつどう' },
    { display: '生徒会', reading: 'せいとかい' },
    { display: '実験', reading: 'じっけん' },
    { display: '観察', reading: 'かんさつ' },
    { display: '発表会', reading: 'はっぴょうかい' },
    { display: '合唱', reading: 'がっしょう' },
    { display: '合奏', reading: 'がっそう' },
    { display: '図画工作', reading: 'ずがこうさく' },
    { display: '書道', reading: 'しょどう' },
    { display: '習字', reading: 'しゅうじ' },
    { display: '計算ドリル', reading: 'けいさんどりる' },
    { display: '漢字ドリル', reading: 'かんじどりる' },
    { display: '読書感想文', reading: 'どくしょかんそうぶん' },
    { display: '自由研究', reading: 'じゆうけんきゅう' },
    { display: '工作', reading: 'こうさく' },
    { display: '校外学習', reading: 'こうがいがくしゅう' },
    { display: '社会科見学', reading: 'しゃかいかけんがく' },
    { display: '球技大会', reading: 'きゅうぎたいかい' },
    { display: '応援団', reading: 'おうえんだん' },
    { display: '徒競走', reading: 'ときょうそう' },
    { display: '騎馬戦', reading: 'きばせん' },
    { display: '綱引き', reading: 'つなひき' },
    { display: '玉入れ', reading: 'たまいれ' },
    { display: '組体操', reading: 'くみたいそう' },
    { display: 'リレー', reading: 'りれー' },
    { display: '保護者会', reading: 'ほごしゃかい' },
    { display: '家庭訪問', reading: 'かていほうもん' },
    { display: '進路相談', reading: 'しんろそうだん' },
    { display: '夏期講習', reading: 'かきこうしゅう' },
    { display: '冬休み', reading: 'ふゆやすみ' },
    { display: '春休み', reading: 'はるやすみ' },
    { display: '始業式', reading: 'しぎょうしき' },
    { display: '終業式', reading: 'しゅうぎょうしき' },
    { display: '通学班', reading: 'つうがくはん' },
    { display: '集団登校', reading: 'しゅうだんとうこう' },
    { display: '保健委員', reading: 'ほけんいいん' },
    { display: '図書委員', reading: 'としょいいん' },
    { display: '飼育係', reading: 'しいくがかり' },
    { display: '黒板', reading: 'こくばん' },
    { display: '机', reading: 'つくえ' },
    { display: '椅子', reading: 'いす' },
    { display: '筆箱', reading: 'ふでばこ' },
    { display: '下校', reading: 'げこう' },
    { display: '登校', reading: 'とうこう' },
  ],
};
